// Generated by generate_fit_coupon.py
// Clearance values are PER SIDE in XY.
// Print with the real interface's printer, nozzle, material, orientation family, and profile.
// This coupon does not prove structural load, creep, fatigue, snap force, or other orientations.
clearances = [0.15, 0.25, 0.35, 0.45];
key_w = 10;
key_d = 6;
engagement = 8;
wall = 3;
base = 2;
lead = 0.8;
bottom_gap = 0.5;
outer_x = 18.5;
outer_y = 14.5;
outer_z = 10;
plug_base_x = 16;
plug_base_y = 12;
plug_base_z = 2;
part_gap = 5;
pitch_x = 23.5;
$fn = 32;
eps = 0.02;

module pocket(c) {
    pocket_w = key_w + 2*c;
    pocket_d = key_d + 2*c;
    lower_h = engagement - lead + eps;
    translate([(outer_x-pocket_w)/2, (outer_y-pocket_d)/2, base])
        cube([pocket_w, pocket_d, lower_h]);
    if (lead > 0) hull() {
        translate([(outer_x-pocket_w)/2, (outer_y-pocket_d)/2, base+engagement-lead])
            cube([pocket_w, pocket_d, eps]);
        translate([(outer_x-(pocket_w+2*lead))/2, (outer_y-(pocket_d+2*lead))/2, base+engagement])
            cube([pocket_w+2*lead, pocket_d+2*lead, eps]);
    }
}

module female(c) {
    difference() {
        cube([outer_x, outer_y, outer_z]);
        pocket(c);
        // Engraved per-side clearance label on the front wall.
        translate([outer_x/2, -eps, base+1.3])
            rotate([-90,0,0])
                linear_extrude(height=0.4+eps)
                    text(str(c), size=2.6, halign="center", valign="center");
    }
}

module male(c) {
    // Print base-down; flip after printing and insert stem-down into the matching pocket.
    union() {
        cube([plug_base_x, plug_base_y, plug_base_z]);
        translate([(plug_base_x-key_w)/2, (plug_base_y-key_d)/2, plug_base_z])
            cube([key_w, key_d, engagement-bottom_gap]);
        translate([plug_base_x/2, (plug_base_y-key_d)/4, plug_base_z])
            linear_extrude(height=0.35)
                text(str(c), size=2.6, halign="center", valign="center");
    }
}

for (i = [0 : len(clearances)-1]) {
    c = clearances[i];
    translate([i*pitch_x, 0, 0]) female(c);
    translate([i*pitch_x + (outer_x-plug_base_x)/2, 19.5, 0]) male(c);
}

echo("per-side clearances mm", clearances);
echo("coupon overall XY mm", len(clearances)*pitch_x-part_gap, 31.5);
