#!/usr/bin/env python3
from __future__ import annotations
import hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]; REV = "0.1.0-draft.1"
PATHS = ["validation/parametric-source-report.json", "validation/mesh-generation-report.json", "validation/interface-report.json", "reports/nesting-layout.json", "validation/optimization-report.json", "validation/fdm-mesh-rack.json", "validation/fdm-mesh-spool-post-gauge.json", "validation/fdm-mesh-bobbin-post-gauge.json", "validation/fdm-3mf-pairpin-eight.json", "validation/slicer-system-020.json", "validation/approvals-through-slicer.json"]
def sha(target): return hashlib.sha256(target.read_bytes()).hexdigest()
def record(target): return {"path": str(target.relative_to(ROOT)), "sha256": sha(target), "size_bytes": target.stat().st_size}
def check(i, passed, message, metrics=None): return {"id": i, "status": "PASS" if passed else "FAIL", "required": True, "message": message, "metrics": metrics or {}, "evidence": []}


def main():
    loaded = {path: json.loads((ROOT / path).read_text()) for path in PATHS}; checks = [check(f"report:{path}", report["status"] == "PASS", f"{path} reports PASS") for path, report in loaded.items()]
    slicer = loaded["validation/slicer-system-020.json"]; gcode = list(slicer["gcode_reports"].values())[0]["metrics"]; native = [item["warning_message"] for item in slicer["native_result"]["sliced_plates"] if item.get("warning_message", "").strip()]; interface = loaded["validation/interface-report.json"]["metrics"]; nesting = loaded["reports/nesting-layout.json"]["metrics"]; optimization = loaded["validation/optimization-report.json"]["metrics"]
    rack = interface["interfaces"]["rack"]
    checks += [check("one-gcode", len(slicer["gcode_reports"]) == 1, "One temporary G-code analysis reports PASS"), check("height", gcode["layers_from_comments"] == 325, "65 mm rack slices as 325 layers at 0.20 mm"), check("warnings", not gcode["warnings"] and not native, "Selected slice is warning-free"), check("one-tool", gcode["tools_seen"] == [0] and gcode["tool_changes"] == 0, "Selected plate uses one tool"), check("pairs", rack["pair_count"] == 8, "Eight aligned pair stations are retained"), check("gauges", interface["interfaces"]["spool-post-gauge"]["candidate_diameters_mm"] == [4, 4.5, 5, 5.5] and interface["interfaces"]["bobbin-post-gauge"]["candidate_diameters_mm"] == [3.5, 4, 4.5, 5], "Both four-pin sweeps are retained"), check("fillets", rack["spool_tip_fillet_mm"] == 1.6 and rack["bobbin_tip_fillet_mm"] == 1.4 and rack["collar_top_fillet_mm"] == 0.8, "Declared contact fillets are retained"), check("nesting", nesting["plate_count"] == 1 and nesting["object_count"] == 3, "Three objects form one plate"), check("optimization", optimization["selected_variant"] == "system-020" and optimization["coarse_volume_delta_percent_vs_020"] > 12, "0.20 mm is selected because coarse extrusion growth exceeds the boundary"), check("physical-deferred", True, "Real bores, machine compatibility, snag, tip, drop and cycles remain user-owned")]
    report = {"schema_version": "1.0", "tool": "MM-ORG-032-finalize-digital-candidate", "tool_version": REV, "status": "PASS" if all(item["status"] == "PASS" for item in checks) else "FAIL", "profile": "draft", "inputs": [record(ROOT / path) for path in PATHS], "checks": checks, "metrics": {"pair_stations": 8, "pin_gauge_stations": 8, "unique_selected_meshes": 3, "selected_objects": 3, "build_plates": 1, "layers": gcode["layers_from_comments"], "slicer_estimate_seconds": gcode["slicer_metadata_time_s"], "extruded_volume_mm3": gcode["extruded_volume_mm3"], "selected_variant": optimization["selected_variant"], "geometric_reduction_vs_proxy_percent": optimization["geometric_reduction_vs_proxy_percent"], "physical_validation": "DEFERRED", "release_state": "DRAFT_DIGITAL_PRINT_CANDIDATE"}, "limitations": ["Print both pin gauges and test only clean real bores before the full rack.", "Verify bobbin machine compatibility from the machine manual separately.", "Adult dry storage only; no thread-feed, tension, universal-fit, load, impact, cycle or child-safety claim.", "No G-code was retained and no printer action occurred."], "required_capabilities": []}
    target = ROOT / "validation/print-candidate-report.json"; target.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n"); print(json.dumps({"status": report["status"], "metrics": report["metrics"]}, indent=2)); raise SystemExit(0 if report["status"] == "PASS" else 1)


if __name__ == "__main__": main()
