#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REV="0.1.0-draft.1"
PATHS=["validation/parametric-source-report.json","validation/mesh-generation-report.json","validation/interface-report.json","reports/template-generation.json","reports/nesting-layout.json","validation/optimization-report.json","validation/fdm-mesh-round-corner.json","validation/fdm-mesh-rectangular-notch.json","validation/fdm-mesh-skewed-corner.json","validation/fdm-mesh-clearance-gauge.json","validation/fdm-mesh-reference-key.json","validation/fdm-3mf-cornerlab-three-presets.json","validation/slicer-system-028.json","validation/approvals-through-slicer.json"]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def record(p): return {"path":str(p.relative_to(ROOT)),"sha256":sha(p),"size_bytes":p.stat().st_size}
def check(i,p,m,x=None): return {"id":i,"status":"PASS" if p else "FAIL","required":True,"message":m,"metrics":x or {},"evidence":[]}
def main():
    loaded={p:json.loads((ROOT/p).read_text()) for p in PATHS}; checks=[check(f"report:{p}",r["status"]=="PASS",f"{p} reports PASS") for p,r in loaded.items()]; slicer=loaded["validation/slicer-system-028.json"]; g=list(slicer["gcode_reports"].values())[0]["metrics"]; native=[i["warning_message"] for i in slicer["native_result"]["sliced_plates"] if i.get("warning_message","").strip()]; interface=loaded["validation/interface-report.json"]["metrics"]; template=loaded["reports/template-generation.json"]["metrics"]; nesting=loaded["reports/nesting-layout.json"]["metrics"]; opt=loaded["validation/optimization-report.json"]["metrics"]
    checks += [check("one-gcode",len(slicer["gcode_reports"])==1,"One temporary G-code analysis reports PASS"),check("height",g["layers_from_comments"]==143,"40 mm trays slice as 143 layers at 0.28 mm"),check("warnings",not g["warnings"] and not native,"Selected slice is warning-free"),check("one-tool",g["tools_seen"]==[0] and g["tool_changes"]==0,"Selected plate uses one tool"),check("three-presets",all(n in interface["interfaces"] for n in ["round-corner","rectangular-notch","skewed-corner"]),"Three corner families are retained"),check("coupon",interface["interfaces"]["clearance-gauge"]["slot_diameters_mm"]==[21,22,23],"Coupon brackets 20 mm key at three clearances"),check("templates",len(template["templates"])==3,"Three exact 1:1 templates are retained"),check("nesting",nesting["plate_count"]==1 and nesting["object_count"]==5,"Five objects form one plate"),check("optimization",opt["selected_variant"]=="system-028" and set(opt["pareto_variants"])=={"system-020","system-028"},"Selected 0.28 mm is an explicit Pareto time-priority choice"),check("physical-deferred",True,"Paper scale, fit, load, drop and cycles remain user-owned")]
    report={"schema_version":"1.0","tool":"MM-ORG-030-finalize-digital-candidate","tool_version":REV,"status":"PASS" if all(c["status"]=="PASS" for c in checks) else "FAIL","profile":"draft","inputs":[record(ROOT/p) for p in PATHS],"checks":checks,"metrics":{"corner_presets":3,"unique_selected_meshes":5,"selected_objects":5,"build_plates":1,"paper_templates":3,"layers":g["layers_from_comments"],"slicer_estimate_seconds":g["slicer_metadata_time_s"],"extruded_volume_mm3":g["extruded_volume_mm3"],"selected_variant":opt["selected_variant"],"geometric_reduction_vs_proxy_percent":opt["geometric_reduction_vs_proxy_percent"],"physical_validation":"DEFERRED","release_state":"DRAFT_DIGITAL_PRINT_CANDIDATE"},"limitations":["Print/measure the 100 mm paper calibration line before tracing.","Print the coupon before any full tray and regenerate clearance if needed.","Dry small-item drawer use only; no load-bearing, liquid, food, hot-item or under-three claim.","No G-code was retained and no printer action occurred."],"required_capabilities":[]}; target=ROOT/"validation/print-candidate-report.json"; target.write_text(json.dumps(report,indent=2,sort_keys=True)+"\n"); print(json.dumps({"status":report["status"],"metrics":report["metrics"]},indent=2)); raise SystemExit(0 if report["status"]=="PASS" else 1)
if __name__=="__main__": main()
