"""Declarative catalog for the FDM mechanical sample library."""
from __future__ import annotations

BASELINE = {
    "units": "mm",
    "nozzle_mm": 0.4,
    "layer_height_mm": 0.2,
    "line_width_mm": 0.45,
    "perimeters": 4,
    "top_bottom_layers": 5,
    "infill_percent": 25,
    "general_materials": ["PLA", "PETG"],
    "flexure_materials": ["PETG", "PA", "PP"],
    "note_de": "Toleranzen sind konstruktive Startwerte pro Seite. Drucker, Material, Flow und Bauteilorientierung müssen mit den Varianten kalibriert werden.",
}


def v(code: str, label: str, note: str, **params):
    return {"code": code, "label_de": label, "note_de": note, "params": params}


FAMILIES = [
    {
        "family": 1,
        "slug": "offset-pin-hinge",
        "title_de": "Versetztes Stiftgelenk",
        "category": "01_rotation_1d",
        "category_de": "Eindimensionale Drehbewegung",
        "module": "sample_pin_hinge",
        "principle_de": "Zwei flach druckbare Gelenkblätter werden axial gestapelt und mit einem herausnehmbaren Stift verbunden.",
        "use_de": "Deckel, Klappen, kleine Robotermechanik und Gehäuse, bei denen ein austauschbarer Gelenkstift gewünscht ist.",
        "integration_de": "Die äußeren Plattenbereiche können in ein Projekt verschmolzen oder über Schraublöcher ergänzt werden. Gelenkachse und Knöchelhöhe unverändert halten.",
        "print_de": "Alle drei Körper stehen bereits druckgerecht. Stift mit mindestens vier Außenlinien drucken.",
        "postprocess_de": "Bohrungen entgraten, Stift trocken einpassen und bei Bedarf leicht polieren.",
        "limitations_de": "Die Blätter liegen axial versetzt. Für hohe Lasten Metallstift und größere Wandstärke verwenden.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil; optional Metallstift gleichen Durchmessers.",
        "part_names": ["Gelenkblatt A", "Gelenkblatt B", "Stift"],
        "variants": [
            v("tight", "eng", "Für sehr gut kalibrierte Drucker.", clearance=0.15, pin_d=4, leaf_l=28),
            v("standard", "standard", "Universeller Startwert für PLA/PETG.", clearance=0.25, pin_d=4, leaf_l=28),
            v("free", "leichtgängig", "Mehr Spiel für raue Oberflächen.", clearance=0.35, pin_d=4, leaf_l=28),
            v("dirty", "schmutztolerant", "Für große Teile, Lack oder staubige Anwendung.", clearance=0.45, pin_d=4, leaf_l=28),
        ],
    },
    {
        "family": 2,
        "slug": "print-in-place-pivot",
        "title_de": "Print-in-Place-Flachdrehgelenk",
        "category": "01_rotation_1d",
        "category_de": "Eindimensionale Drehbewegung",
        "module": "sample_pip_pivot",
        "principle_de": "Ein C-förmiger Außenring hält einen getrennt gedruckten Innenzapfen; beide Körper entstehen in einer Druckoperation.",
        "use_de": "Flache Klappen, Zeiger, kleine Hebel und Demonstratoren mit begrenztem Drehwinkel.",
        "integration_de": "Die beiden Anschlussplatten dürfen verlängert werden; radialen Spalt und C-Öffnung nicht schließen.",
        "print_de": "Als gemeinsame `print_plate.stl` drucken, nicht als separat platzierte Körper. Erste Schicht nicht überquetschen.",
        "postprocess_de": "Nach dem Abkühlen vorsichtig lösen und mehrfach bewegen.",
        "limitations_de": "Begrenzter Drehwinkel; starkes Elephant-Foot kann die Körper verbinden.",
        "materials": ["PLA", "PETG"],
        "hardware": "Kein Fremdteil.",
        "must_print_as_plate": True,
        "part_names": ["Außenring mit Blatt", "Innenzapfen mit Blatt"],
        "variants": [
            v("020", "0,20 mm", "Eng für kalibrierte PLA-Drucke.", clearance=0.20, core_d=8),
            v("025", "0,25 mm", "Standard für gute Drucker.", clearance=0.25, core_d=8),
            v("030", "0,30 mm", "Robuster Start für PETG.", clearance=0.30, core_d=8),
            v("040", "0,40 mm", "Großzügig bei Elephant-Foot oder grober Düse.", clearance=0.40, core_d=8),
        ],
    },
    {
        "family": 3,
        "slug": "thin-section-flexure-hinge",
        "title_de": "Dünnsteg-Festkörpergelenk",
        "category": "01_rotation_1d",
        "category_de": "Eindimensionale Drehbewegung",
        "module": "sample_flexure_hinge",
        "principle_de": "Zwei starre Platten sind durch einen lokal dünnen, biegeweichen Steg verbunden.",
        "use_de": "Kleine Ausschläge ohne Spiel, Sensorhalter, Justageelemente und selten betätigte Deckel.",
        "integration_de": "Den Steg entlang der vorgesehenen Biegeachse ausrichten und Kerben oder scharfe Ecken vermeiden.",
        "print_de": "Flach drucken. Für wiederholte Biegung PETG, PA oder PP bevorzugen; 100 % Linienfüllung im Steg.",
        "postprocess_de": "Langsam einbiegen und maximalen Winkel schrittweise bestimmen.",
        "limitations_de": "Kein endlos rotierendes Gelenk; Lebensdauer hängt stark von Material, Layerhaftung und Winkel ab.",
        "materials": ["PETG", "PA", "PP"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Festkörpergelenk"],
        "variants": [
            v("soft", "weich 0,6 mm", "Hohe Beweglichkeit, geringe Last.", beam_t=0.6, beam_w=12, gap=8),
            v("balanced", "ausgewogen 0,8 mm", "Guter Start für PETG.", beam_t=0.8, beam_w=12, gap=8),
            v("stiff", "steif 1,0 mm", "Mehr Rückstellkraft.", beam_t=1.0, beam_w=12, gap=8),
            v("heavy", "kräftig 1,2 mm", "Nur für kleine Winkel und zähe Werkstoffe.", beam_t=1.2, beam_w=12, gap=8),
        ],
    },
    {
        "family": 4,
        "slug": "serpentine-living-hinge",
        "title_de": "Serpentinen-Filmgelenk",
        "category": "01_rotation_1d",
        "category_de": "Eindimensionale Drehbewegung",
        "module": "sample_serpentine_hinge",
        "principle_de": "Zwei meanderförmige Federbahnen verteilen die Dehnung über eine längere Strecke.",
        "use_de": "Wiederholt betätigte leichte Klappen, flexible Verbinder und Bewegungsentkopplung.",
        "integration_de": "Die Anschlussplatten anpassen, die Serpentinen aber nicht lokal verdicken oder durch Texturen schwächen.",
        "print_de": "Flach, ohne Support. Extrusionsbreite und Bahnbreite müssen zueinander passen.",
        "postprocess_de": "Langsam zyklisch einfahren; keine scharfen Knicke erzwingen.",
        "limitations_de": "Nicht für hohe Kräfte oder hohe Temperatur; PLA ermüdet schneller.",
        "materials": ["PETG", "PA", "PP"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Serpentinen-Gelenk"],
        "variants": [
            v("080", "0,8 mm Bahn", "Sehr weich, mindestens zwei Extrusionslinien prüfen.", beam_w=0.8, gap=22),
            v("100", "1,0 mm Bahn", "Leichte, gut druckbare Variante.", beam_w=1.0, gap=22),
            v("120", "1,2 mm Bahn", "Ausgewogener Standard.", beam_w=1.2, gap=22),
            v("150", "1,5 mm Bahn", "Kräftige Rückstellung bei kleinerem Weg.", beam_w=1.5, gap=22),
        ],
    },
    {
        "family": 5,
        "slug": "snap-universal-joint",
        "title_de": "Schnapp-Kardangelenk",
        "category": "02_movement_2d",
        "category_de": "Zweiachsige Bewegung",
        "module": "sample_universal_joint",
        "principle_de": "Zwei orthogonale Schnappgabeln greifen einen Kreuzkörper und ermöglichen Kippung um zwei Achsen.",
        "use_de": "Leichte Wellenumlenkung, Joysticks, Kamerahalter und Demonstratoren.",
        "integration_de": "Gabelbasen in das Projekt einarbeiten; Kreuzspannweite, Zapfendurchmesser und Schnappschlitze gemeinsam skalieren.",
        "print_de": "Gabeln flach, Kreuz separat. PETG erleichtert das Einschnappen.",
        "postprocess_de": "Schnappschlitze entgraten, Kreuz erst in eine und dann in die zweite Gabel drücken.",
        "limitations_de": "Nicht für hohe Drehmomente oder hohe Drehzahl; keine homokinetische Kupplung.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Gabel A", "Gabel B", "Kreuz"],
        "variants": [
            v("tight", "eng", "Minimales Spiel.", clearance=0.20, pin_d=4),
            v("standard", "standard", "Guter PETG-Startwert.", clearance=0.30, pin_d=4),
            v("free", "leichtgängig", "Einfachere Montage.", clearance=0.40, pin_d=4),
            v("loose", "großzügig", "Für grobe Oberflächen oder Lack.", clearance=0.50, pin_d=4),
        ],
    },
    {
        "family": 6,
        "slug": "pinned-gimbal",
        "title_de": "Zweiachsiger Gimbal mit Stiften",
        "category": "02_movement_2d",
        "category_de": "Zweiachsige Bewegung",
        "module": "sample_gimbal_joint",
        "principle_de": "Außenrahmen, Innenrahmen und Plattform drehen um zwei orthogonale, herausnehmbare Stifte.",
        "use_de": "Sensor-, Kamera- und Antennenhalter, Joystick- oder Nivelliermechanik.",
        "integration_de": "Außenrahmen befestigen; Plattformfläche an das Nutzteil anpassen. Achsen müssen orthogonal bleiben.",
        "print_de": "Rahmen flach, Stifte stehend. Kleine horizontale Bohrungen langsam drucken.",
        "postprocess_de": "Bohrungen mit Handreibahle oder passendem Bohrer nur leicht kalibrieren.",
        "limitations_de": "Druckstifte sind für Demonstration; für dauerhafte Last Metallstifte verwenden.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Optional zwei Metallstifte.",
        "part_names": ["Außenrahmen", "Innenrahmen", "Plattform", "Achsstift X", "Achsstift Y"],
        "variants": [
            v("tight", "eng", "Präzise, eventuell Nachreiben nötig.", clearance=0.20, pin_d=4),
            v("standard", "standard", "Ausgewogener Startwert.", clearance=0.30, pin_d=4),
            v("free", "leichtgängig", "Mehr Bewegungsfreiheit.", clearance=0.40, pin_d=4),
            v("loose", "großzügig", "Für abrasive Materialien oder Beschichtung.", clearance=0.50, pin_d=4),
        ],
    },
    {
        "family": 7,
        "slug": "xy-flexure-stage",
        "title_de": "XY-Festkörpertisch",
        "category": "02_movement_2d",
        "category_de": "Zweiachsige Bewegung",
        "module": "sample_xy_flexure_stage",
        "principle_de": "Gefaltete Federstege führen eine zentrale Plattform mit kleinem, spielfreiem Weg in X und Y.",
        "use_de": "Feinpositionierung, Sensorentkopplung, optische Demonstratoren und kleine Greifer.",
        "integration_de": "Außenrahmen fixieren und Last mittig auf der Plattform einleiten. Federbahnen nicht bohren.",
        "print_de": "Flach und ohne Support. Zähe Werkstoffe und gute Layerhaftung verwenden.",
        "postprocess_de": "Mit kleinen Wegen einfahren und mechanische Anschläge im Projekt vorsehen.",
        "limitations_de": "Nur kleiner Hub; nicht für freie Rotation oder hohe Querlasten.",
        "materials": ["PETG", "PA", "PP"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["XY-Festkörpertisch"],
        "variants": [
            v("soft", "weich 0,8 mm", "Großer Weg bei geringer Kraft.", beam_w=0.8, beam_l=17),
            v("balanced", "ausgewogen 1,0 mm", "Guter Start für PETG.", beam_w=1.0, beam_l=17),
            v("stiff", "steif 1,2 mm", "Mehr Rückstellkraft.", beam_w=1.2, beam_l=17),
            v("heavy", "kräftig 1,5 mm", "Kleiner Weg, höhere Last.", beam_w=1.5, beam_l=17),
        ],
    },
    {
        "family": 8,
        "slug": "slotted-snap-ball-joint",
        "title_de": "Geschlitztes Schnapp-Kugelgelenk",
        "category": "03_ball_joints",
        "category_de": "Kugelgelenke",
        "module": "sample_snap_ball_joint",
        "principle_de": "Eine geschlitzte Kugelpfanne federt beim Einpressen auf und hält den Kugelzapfen formschlüssig.",
        "use_de": "Verstellbare Halter, Leuchten, Sensoren, Figuren und kleine Gestänge.",
        "integration_de": "Sockelplatten ersetzen oder verschmelzen; Kugeldurchmesser, Pfannenwand und Öffnung gemeinsam anpassen.",
        "print_de": "Pfanne mit Öffnung nach oben; Kugelzapfen stehend. Für die Pfanne PETG oder PA bevorzugen. Je nach Drucker kann eine kleine organische Stütze nur unter der unteren Kugelhälfte die Rundheit verbessern; Kontaktflächen der Pfanne supportfrei lassen.",
        "postprocess_de": "Schlitze säubern, Kugel mit gleichmäßiger Kraft gerade einschnappen und anschließend bewegen.",
        "limitations_de": "Haltekraft hängt stark vom Material ab; nicht für sicherheitsrelevante Lasten.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Kugelpfanne", "Kugelzapfen"],
        "variants": [
            v("tight", "eng", "Hohe Haltekraft, anspruchsvolle Montage.", ball_d=14, clearance=0.25),
            v("standard", "standard", "Ausgewogener Startwert.", ball_d=14, clearance=0.35),
            v("free", "leichtgängig", "Geringere Reibung.", ball_d=14, clearance=0.45),
            v("loose", "großzügig", "Für raue Materialien oder Beschichtung.", ball_d=14, clearance=0.55),
        ],
    },
    {
        "family": 9,
        "slug": "split-clamp-ball-joint",
        "title_de": "Geteilte Klemm-Kugelpfanne",
        "category": "03_ball_joints",
        "category_de": "Kugelgelenke",
        "module": "sample_clamp_ball_joint",
        "principle_de": "Zwei Pfannenhälften umschließen die Kugel und stellen Reibung über Schrauben ein.",
        "use_de": "Belastbarere Kamera-, Sensor- und Leuchtenhalter mit nachstellbarer Klemmung.",
        "integration_de": "Pfannenhälften über ihre Außenflächen anbinden; Schraubenachsen und Trennfuge freihalten.",
        "print_de": "Hälften mit Kugelmulde nach oben, Kugelzapfen stehend. Vier Außenlinien empfohlen. Eine kleine organische Stütze nur unter der unteren Kugelhälfte ist optional, wenn die Rundheit wichtiger als supportfreier Druck ist.",
        "postprocess_de": "Mit zwei Schrauben gleichmäßig anziehen; nicht überklemmen.",
        "limitations_de": "Benötigt Schrauben und Muttern; Kugeloberfläche zeigt FDM-Schichtstufen.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Zwei M3-Schrauben und M3-Muttern pro Muster.",
        "part_names": ["Pfannenhälfte A", "Pfannenhälfte B", "Kugelzapfen"],
        "variants": [
            v("d12", "Kugel 12 mm", "Kompakte Halterung.", ball_d=12, clearance=0.25),
            v("d14", "Kugel 14 mm", "Leichte Standardgröße.", ball_d=14, clearance=0.25),
            v("d16", "Kugel 16 mm", "Robuster Allrounder.", ball_d=16, clearance=0.25),
            v("d20", "Kugel 20 mm", "Größere Klemmfläche.", ball_d=20, clearance=0.30),
        ],
    },
    {
        "family": 10,
        "slug": "press-fit-dowel",
        "title_de": "Dauerhafter Pressstift",
        "category": "04_permanent_connections",
        "category_de": "Dauerhafte Steck- und Schiebverbindungen",
        "module": "sample_pressfit_dowel",
        "principle_de": "Ein konischer Einlauf führt einen zylindrischen Stift in eine kalibrierte Bohrung.",
        "use_de": "Dauerhafte Positionierung, Gehäusehälften, Montagehilfen und Klebeverbindungen.",
        "integration_de": "Stift und Bohrung entlang einer belastbaren Wand platzieren; ausreichend Material um die Bohrung vorsehen.",
        "print_de": "Stift und Bohrung vertikal. Flow und Elephant-Foot beeinflussen die Passung stark.",
        "postprocess_de": "Trocken testen; für dauerhafte Verbindung bei Bedarf Klebstoff verwenden.",
        "limitations_de": "Negative Werte erzeugen Interferenz und können spröde Teile spalten.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Buchse", "Stiftplatte"],
        "variants": [
            v("i015", "0,15 mm Übermaß", "Kräftiger Presssitz für zähe Werkstoffe.", pin_d=8, gap=-0.15),
            v("i005", "0,05 mm Übermaß", "Moderater Presssitz.", pin_d=8, gap=-0.05),
            v("line", "Nennmaß", "Kalibrierprobe ohne konstruktives Spiel.", pin_d=8, gap=0.0),
            v("g010", "0,10 mm Spiel", "Leichte Montage oder Klebespalt.", pin_d=8, gap=0.10),
        ],
    },
    {
        "family": 11,
        "slug": "keyed-plug-socket",
        "title_de": "Verdrehsichere Schlüssel-Steckverbindung",
        "category": "04_permanent_connections",
        "category_de": "Dauerhafte Steck- und Schiebverbindungen",
        "module": "sample_keyed_plug_socket",
        "principle_de": "Ein rechteckiger Steckzapfen mit Seitenfeder verhindert falsche Orientierung und Verdrehung.",
        "use_de": "Modulare Gehäuse, Sensormodule und verklebte Baugruppen.",
        "integration_de": "Sockel durch Projektgeometrie ersetzen; Schlüsselposition als Montagekodierung nutzen.",
        "print_de": "Zapfen und Buchse stehend, Einlauf entgraten.",
        "postprocess_de": "Passung testen und bei permanenter Montage verkleben oder thermisch sichern.",
        "limitations_de": "Nicht selbstverriegelnd; Zugkräfte benötigen zusätzliche Sicherung.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Buchse", "Schlüsselzapfen"],
        "variants": [
            v("015", "0,15 mm", "Sehr genaue Passung.", clearance=0.15),
            v("025", "0,25 mm", "Standard.", clearance=0.25),
            v("035", "0,35 mm", "Leichte Montage.", clearance=0.35),
            v("045", "0,45 mm", "Für Beschichtung oder grobe Extrusion.", clearance=0.45),
        ],
    },
    {
        "family": 12,
        "slug": "barbed-one-way-connector",
        "title_de": "Einweg-Steckverbinder mit Widerhaken",
        "category": "04_permanent_connections",
        "category_de": "Dauerhafte Steck- und Schiebverbindungen",
        "module": "sample_barbed_connector",
        "principle_de": "Tapered Widerhaken passieren eine geschlitzte Buchse und erschweren das Zurückziehen.",
        "use_de": "Einmalmontage, Gehäuseclips, leichte Rohr- oder Kabelmodule.",
        "integration_de": "Buchsenwand und Schlitze in der belasteten Richtung orientieren; Ausbauzugang bewusst ausschließen oder vorsehen.",
        "print_de": "Beide Teile stehend. Buchse aus PETG/PA für elastische Finger.",
        "postprocess_de": "Nur nach erfolgreicher Kalibrierung vollständig einpressen; Verbindung ist schwer lösbar.",
        "limitations_de": "Demontage kann Bauteile beschädigen. Nicht für Druckleitungen.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Geschlitzte Buchse", "Widerhakenstift"],
        "variants": [
            v("015", "0,15 mm", "Hohe Haltekraft.", clearance=0.15, pin_d=7, barb_h=1.0),
            v("025", "0,25 mm", "Standard.", clearance=0.25, pin_d=7, barb_h=1.0),
            v("035", "0,35 mm", "Einfachere Montage.", clearance=0.35, pin_d=7, barb_h=1.0),
            v("045", "0,45 mm", "Für zähe oder grobe Drucke.", clearance=0.45, pin_d=7, barb_h=0.9),
        ],
    },
    {
        "family": 13,
        "slug": "dovetail-joiner",
        "title_de": "Schwalbenschwanz-Verbinder",
        "category": "04_permanent_connections",
        "category_de": "Dauerhafte Steck- und Schiebverbindungen",
        "module": "sample_dovetail_joiner",
        "principle_de": "Trapezförmige Flanken übertragen Zug quer zur Einschubrichtung und führen zwei Bauteile linear.",
        "use_de": "Gehäusemodule, Möbelmodelle, Abdeckungen und verklebbare Schiebverbindungen.",
        "integration_de": "Profil entlang einer geraden, gut zugänglichen Einschubrichtung anordnen; Endanschlag ergänzen.",
        "print_de": "Beide Profile flach; keine Supports. Flanken mit geringer Geschwindigkeit drucken.",
        "postprocess_de": "Flanken entgraten und von der offenen Seite einschieben.",
        "limitations_de": "Interferenzvariante kann nur einmal montierbar sein; lange Profile reagieren auf Verzug.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Buchsenprofil", "Schwalbenschwanzprofil"],
        "variants": [
            v("interference", "leichte Interferenz", "Dauerhafte Press-Schiebeverbindung.", clearance=-0.05, length=42),
            v("tight", "eng 0,10 mm", "Präziser Sitz.", clearance=0.10, length=42),
            v("standard", "standard 0,20 mm", "Guter Startwert.", clearance=0.20, length=42),
            v("free", "leichtgängig 0,35 mm", "Wiederholbare Montage.", clearance=0.35, length=42),
        ],
    },
    {
        "family": 14,
        "slug": "transverse-wedge-lock",
        "title_de": "Nut-Feder-Verbindung mit Querkeil",
        "category": "04_permanent_connections",
        "category_de": "Dauerhafte Steck- und Schiebverbindungen",
        "module": "sample_wedge_lock_joint",
        "principle_de": "Eine geführte Zunge wird eingeschoben und anschließend durch einen separaten Querkeil gegen Rückzug gesichert.",
        "use_de": "Zerlegbare Rahmen, Gehäusemodule und Bauteile ohne Metallbefestiger.",
        "integration_de": "Querkeilzugang offen halten und Lastpfad nicht allein auf die dünne Keilspitze legen.",
        "print_de": "Alle Teile flach; Keil mit vielen Außenlinien drucken.",
        "postprocess_de": "Zunge einschieben, Fenster ausrichten, Keil von der breiten Seite eintreiben.",
        "limitations_de": "Keil kann sich unter Vibration lösen; optional Fanglasche ergänzen.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Nutkörper", "Zungenkörper", "Querkeil"],
        "variants": [
            v("015", "0,15 mm", "Enger Sitz.", clearance=0.15),
            v("025", "0,25 mm", "Standard.", clearance=0.25),
            v("035", "0,35 mm", "Leichte Montage.", clearance=0.35),
            v("045", "0,45 mm", "Großzügig für raue Materialien.", clearance=0.45),
        ],
    },
    {
        "family": 15,
        "slug": "captured-nut-screw-boss",
        "title_de": "Schraubdom mit seitlicher Muttertasche",
        "category": "05_screw_connections",
        "category_de": "Schraubverbindungen",
        "module": "sample_nuttrap_screw",
        "principle_de": "Eine Sechskantmutter wird seitlich in einen Dom eingeschoben und durch einen Deckel verschraubt.",
        "use_de": "Gehäuse, Wartungsdeckel, Elektronikhalter und wieder lösbare Baugruppen.",
        "integration_de": "Dom mit Rippen an tragende Wände anbinden und Schraubenlänge an Projektstärke anpassen.",
        "print_de": "Muttertasche und Bohrung vertikal. Keine Supports nötig.",
        "postprocess_de": "Mutter einschieben, Schraube von Hand ansetzen und nicht überdrehen.",
        "limitations_de": "Abmessungen sind typische Startwerte; reale Muttern und Schraubenköpfe messen.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Je Variante passende Schraube und Sechskantmutter.",
        "part_names": ["Mutterdom", "Deckel"],
        "variants": [
            v("m25", "M2,5", "Kompakte Elektronikmontage.", screw_d=2.9, nut_flat=5.0, nut_h=2.1, head_d=5.2),
            v("m3", "M3", "Allgemeiner Standard.", screw_d=3.4, nut_flat=5.7, nut_h=2.5, head_d=6.5),
            v("m4", "M4", "Robustere Gehäuse.", screw_d=4.5, nut_flat=7.2, nut_h=3.3, head_d=8.3),
            v("m5", "M5", "Größere mechanische Baugruppen.", screw_d=5.5, nut_flat=8.4, nut_h=4.2, head_d=9.6),
        ],
    },
    {
        "family": 16,
        "slug": "heat-set-insert-coupon",
        "title_de": "Heizeinsatz-Schraubprobe",
        "category": "05_screw_connections",
        "category_de": "Schraubverbindungen",
        "module": "sample_heatset_insert",
        "principle_de": "Ein abgestufter Pilotkanal nimmt einen Messing-Heizeinsatz auf; der Deckel prüft die Schraubverbindung.",
        "use_de": "Kalibrierung von Heat-Set-Inserts vor dem Einbau in Gehäuse und Funktionsteile.",
        "integration_de": "Domdurchmesser und Restwandstärke beibehalten; reale Insert-Zeichnung als Autorität verwenden.",
        "print_de": "Dom stehend. Mindestens vier Außenlinien und 40 % lokales Infill.",
        "postprocess_de": "Insert mit temperaturgeregeltem Werkzeug rechtwinklig einsetzen und vollständig abkühlen lassen.",
        "limitations_de": "Pilotmaße sind generisch; Herstellergeometrien unterscheiden sich deutlich.",
        "materials": ["PETG", "ABS", "ASA", "PA", "PLA"],
        "hardware": "Passender Messing-Heizeinsatz und Schraube.",
        "part_names": ["Insert-Dom", "Prüfdeckel"],
        "variants": [
            v("m2", "M2", "Pilot für kleine Inserts.", pilot_d=3.2, screw_clear=2.4, head_d=4.4, insert_depth=4.0),
            v("m25", "M2,5", "Pilot für kompakte Inserts.", pilot_d=3.8, screw_clear=2.9, head_d=5.2, insert_depth=5.0),
            v("m3", "M3", "Häufiger Standard.", pilot_d=4.2, screw_clear=3.4, head_d=6.5, insert_depth=6.0),
            v("m4", "M4", "Größerer Heizeinsatz.", pilot_d=5.6, screw_clear=4.5, head_d=8.3, insert_depth=7.0),
        ],
    },
    {
        "family": 17,
        "slug": "coarse-printed-thread",
        "title_de": "Grobgewinde aus dem Drucker",
        "category": "05_screw_connections",
        "category_de": "Schraubverbindungen",
        "module": "sample_printed_thread",
        "principle_de": "Ein großes einstufiges Helixprofil bildet eine direkt druckbare Schraube und Mutter.",
        "use_de": "Werkzeuglose Deckel, Versteller, Klemmen und große Handverschraubungen.",
        "integration_de": "Gewindelänge, Anlauf und Wandstärke anpassen; keine kleinen Metallgewinde imitieren.",
        "print_de": "Stehend mit kleiner Schichthöhe. Nahtposition möglichst vom Lastbereich weglegen.",
        "postprocess_de": "Gewinde reinigen, mehrfach vorsichtig ein- und ausschrauben; trockenes PTFE kann helfen.",
        "limitations_de": "Profil ist FDM-optimiert, nicht normgerecht. Nicht für Druckbehälter oder hohe Vorspannung.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Mutter", "Schraube"],
        "variants": [
            v("d12", "Ø 12 / P 2,5", "Kompaktes Grobgewinde.", d=12, pitch=2.5, clearance=0.25, length=14),
            v("d16", "Ø 16 / P 3", "Allgemeiner Standard.", d=16, pitch=3.0, clearance=0.30, length=16),
            v("d20", "Ø 20 / P 4", "Robust und gut greifbar.", d=20, pitch=4.0, clearance=0.35, length=18),
            v("d24", "Ø 24 / P 5", "Große Handverschraubung.", d=24, pitch=5.0, clearance=0.45, length=20),
        ],
    },
    {
        "family": 18,
        "slug": "cantilever-snap-latch",
        "title_de": "Wiederlösbarer Kragarm-Schnapper",
        "category": "06_reusable_closures",
        "category_de": "Periodisch lösbare Verschlüsse",
        "module": "sample_cantilever_snap",
        "principle_de": "Ein elastischer Kragarm wird beim Einschieben ausgelenkt und rastet hinter einem Fenster ein.",
        "use_de": "Gehäusedeckel, Batteriefächer, austauschbare Module und Kabelabdeckungen.",
        "integration_de": "Am Kragarmansatz großzügige Radien vorsehen und eine Finger- oder Werkzeugfreigabe zum Lösen erhalten.",
        "print_de": "Kragarm flach in Layer-Ebene; PETG/PA für Wiederholzyklen.",
        "postprocess_de": "Kanten entgraten und zunächst mit kleinem Weg testen.",
        "limitations_de": "PLA kann bei Dauerverformung kriechen oder brechen.",
        "materials": ["PETG", "PA", "PP", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Rastfenster", "Kragarmhaken"],
        "variants": [
            v("soft", "weich 0,8 mm", "Leicht zu lösen.", beam_t=0.8, clearance=0.25, hook=1.6),
            v("balanced", "ausgewogen 1,0 mm", "Guter PETG-Start.", beam_t=1.0, clearance=0.25, hook=1.8),
            v("standard", "standard 1,2 mm", "Kräftiger Halt.", beam_t=1.2, clearance=0.25, hook=2.0),
            v("heavy", "kräftig 1,5 mm", "Nur zähe Werkstoffe und geringe Auslenkung.", beam_t=1.5, clearance=0.30, hook=2.2),
        ],
    },
    {
        "family": 19,
        "slug": "rotating-hook-latch",
        "title_de": "Drehhakenverschluss",
        "category": "06_reusable_closures",
        "category_de": "Periodisch lösbare Verschlüsse",
        "module": "sample_hook_latch",
        "principle_de": "Ein drehbarer Haken greift hinter einen separaten Fangblock und wird durch einen Stift geführt.",
        "use_de": "Kisten, Klappen, Modellbau und wiederholt zu öffnende Abdeckungen.",
        "integration_de": "Grundplatte und Fangblock auf derselben Bezugsebene montieren; Hebelweg freihalten.",
        "print_de": "Alle Teile flach, Stift stehend.",
        "postprocess_de": "Stift einsetzen, Hebelspiel prüfen und optional mit Kopf oder Clip sichern.",
        "limitations_de": "Kein Über-Center-Effekt; bei Vibration zusätzliche Rastung vorsehen.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil; optional Metallstift.",
        "part_names": ["Drehbasis", "Hakenhebel", "Fangblock", "Stift"],
        "variants": [
            v("015", "0,15 mm", "Enger Hebelsitz.", pin_d=4, clearance=0.15, arm=34),
            v("025", "0,25 mm", "Standard.", pin_d=4, clearance=0.25, arm=34),
            v("035", "0,35 mm", "Leichtgängig.", pin_d=4, clearance=0.35, arm=34),
            v("045", "0,45 mm", "Für raue Oberflächen.", pin_d=4, clearance=0.45, arm=34),
        ],
    },
    {
        "family": 20,
        "slug": "bayonet-quarter-turn",
        "title_de": "Bajonett-Vierteldrehverschluss",
        "category": "06_reusable_closures",
        "category_de": "Periodisch lösbare Verschlüsse",
        "module": "sample_bayonet",
        "principle_de": "Radiale Nasen werden axial eingeführt und durch eine kurze Drehung in seitliche Kanäle verschoben.",
        "use_de": "Deckel, Filterhalter, Sensoradapter und schnell wechselbare Module.",
        "integration_de": "Einführ- und Drehanschlag sichtbar halten; bei Axialvorspannung Rampen oder Dichtung ergänzen.",
        "print_de": "Stehend. Kanalüberhänge sind kurz, kleine Schichthöhe verbessert die Bewegung.",
        "postprocess_de": "Kanäle entgraten, axial einführen und etwa 35–45° drehen.",
        "limitations_de": "Ohne Feder oder Dichtung keine selbsttätige Vorspannung gegen Klappern.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Bajonettbuchse", "Bajonettstecker"],
        "variants": [
            v("020", "0,20 mm", "Enger Sitz.", core_d=18, clearance=0.20, lug_w=5),
            v("030", "0,30 mm", "Standard.", core_d=18, clearance=0.30, lug_w=5),
            v("040", "0,40 mm", "Leichtgängig.", core_d=18, clearance=0.40, lug_w=5),
            v("050", "0,50 mm", "Für Beschichtung und große Teile.", core_d=18, clearance=0.50, lug_w=5),
        ],
    },
    {
        "family": 21,
        "slug": "sliding-bolt-latch",
        "title_de": "Linearer Schubriegel",
        "category": "06_reusable_closures",
        "category_de": "Periodisch lösbare Verschlüsse",
        "module": "sample_slide_bolt",
        "principle_de": "Ein T-förmig geführter Riegel bewegt sich linear zwischen Basis und separatem Fangstück.",
        "use_de": "Türen, Schubladen, Modellbauklappen und Transportsicherungen.",
        "integration_de": "Basis und Fangstück fluchten lassen; Griffweg und Anschläge erhalten.",
        "print_de": "Alle Teile flach und supportfrei.",
        "postprocess_de": "Führungen entgraten, Riegel einschieben und Fangstück ausrichten.",
        "limitations_de": "Keine automatische Verriegelung; bei Vibration Rastnase oder Magnet ergänzen.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Riegelführung", "Riegel", "Fangstück"],
        "variants": [
            v("015", "0,15 mm", "Präzise Führung.", clearance=0.15, bolt_w=10, bolt_h=5),
            v("025", "0,25 mm", "Standard.", clearance=0.25, bolt_w=10, bolt_h=5),
            v("035", "0,35 mm", "Leichtgängig.", clearance=0.35, bolt_w=10, bolt_h=5),
            v("045", "0,45 mm", "Schmutztolerant.", clearance=0.45, bolt_w=10, bolt_h=5),
        ],
    },
    {
        "family": 22,
        "slug": "dovetail-linear-rail",
        "title_de": "Schwalbenschwanz-Linearführung",
        "category": "07_linear_motion",
        "category_de": "Periodische Linearbewegung",
        "module": "sample_dovetail_rail",
        "principle_de": "Ein langer Schwalbenschwanz führt einen geschlossenen Schlitten und nimmt Querkräfte auf.",
        "use_de": "Versteller, Schubladen, Sensorpositionierung und modulare Vorrichtungen.",
        "integration_de": "Schiene möglichst gerade und entlang der Druckbahnen orientieren; Anschläge und Schmierzugang vorsehen.",
        "print_de": "Schiene und Schlitten flach. Verzug der langen Schiene vermeiden.",
        "postprocess_de": "Flanken leicht entgraten und mit trockenem PTFE oder Wachs einlaufen lassen.",
        "limitations_de": "FDM-Flanken sind keine Präzisionsführung; Spiel und Verschleiß kalibrieren.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Schiene", "Schlitten"],
        "variants": [
            v("020", "0,20 mm", "Eng für kurze, präzise Führungen.", clearance=0.20, length=70, carriage_l=26),
            v("030", "0,30 mm", "Standard.", clearance=0.30, length=70, carriage_l=26),
            v("040", "0,40 mm", "Leichtgängig.", clearance=0.40, length=70, carriage_l=26),
            v("050", "0,50 mm", "Für lange Schienen oder grobe Materialien.", clearance=0.50, length=70, carriage_l=26),
        ],
    },
    {
        "family": 23,
        "slug": "mushroom-t-linear-rail",
        "title_de": "Pilzkopf-/T-Linearführung",
        "category": "07_linear_motion",
        "category_de": "Periodische Linearbewegung",
        "module": "sample_t_rail",
        "principle_de": "Ein Pilzkopfprofil hält den Schlitten gegen Abheben und bietet breite horizontale Führungsflächen.",
        "use_de": "Schiebedeckel, leichte Schlitten und wechselbare Module.",
        "integration_de": "Profil an beiden Enden zugänglich lassen oder Schlitten vor dem Verschließen montieren.",
        "print_de": "Flach; 45°-Unterseiten reduzieren Supportbedarf.",
        "postprocess_de": "Kanten brechen, einschieben und Reibung über Variante wählen.",
        "limitations_de": "Unterzüge sind druckerabhängig; nicht für hohe Biegemomente.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["T-Schiene", "T-Schlitten"],
        "variants": [
            v("020", "0,20 mm", "Enger Sitz.", clearance=0.20, length=70, carriage_l=26),
            v("030", "0,30 mm", "Standard.", clearance=0.30, length=70, carriage_l=26),
            v("040", "0,40 mm", "Leichtgängig.", clearance=0.40, length=70, carriage_l=26),
            v("050", "0,50 mm", "Großzügig für lange Zyklen.", clearance=0.50, length=70, carriage_l=26),
        ],
    },
    {
        "family": 24,
        "slug": "compliant-preload-slider",
        "title_de": "Vorgespannter Feder-Schlitten",
        "category": "07_linear_motion",
        "category_de": "Periodische Linearbewegung",
        "module": "sample_preload_slider",
        "principle_de": "Dünne Dachfedern drücken den Schlitten gegen eine Rechteckschiene und reduzieren Klappern.",
        "use_de": "Leichte Kameraschlitten, Sensorführungen und handbetätigte Versteller.",
        "integration_de": "Federbereiche frei halten; Schiene mit definierten glatten Kontaktflächen verlängern.",
        "print_de": "Schlitten wie geliefert drucken. PETG/PA für Federbahnen bevorzugen.",
        "postprocess_de": "Schlitten von einem Ende aufschieben und Federvorspannung langsam einfahren.",
        "limitations_de": "Reibung steigt mit Vorspannung; Federkriechen bei Wärme beachten.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Rechteckschiene", "Federschlitten"],
        "variants": [
            v("soft", "weich", "Geringe Reibung und kleine Vorspannung.", clearance=0.25, beam_t=0.8),
            v("balanced", "ausgewogen", "Guter PETG-Startwert.", clearance=0.35, beam_t=1.0),
            v("stiff", "steif", "Mehr Spielfreiheit, höhere Reibung.", clearance=0.45, beam_t=1.2),
            v("rugged", "robust", "Großer Grundspalt mit kräftigen Federn.", clearance=0.55, beam_t=1.4),
        ],
    },
    {
        "family": 25,
        "slug": "rack-and-pinion",
        "title_de": "Zahnstange und Ritzel",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_rack_pinion",
        "principle_de": "Ein grob druckbares Ritzel wandelt Drehung in lineare Zahnstangenbewegung um.",
        "use_de": "Versteller, Greifer, Schieber, Demonstratoren und langsam bewegte Modellmechanik.",
        "integration_de": "Achsabstand im Projekt einstellbar machen; Zahnstange seitlich führen und Endanschläge ergänzen.",
        "print_de": "Zahnstange und Ritzel flach. Kleine Schichthöhe verbessert Zahnflanken.",
        "postprocess_de": "Zähne entgraten und Achsabstand so einstellen, dass kein Klemmen entsteht.",
        "limitations_de": "Vereinfachtes FDM-Zahnprofil, nicht für hohe Drehzahl oder exakte Übersetzung.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil; optional Metallachse.",
        "part_names": ["Zahnstange", "Ritzel", "Achsstift"],
        "variants": [
            v("m125", "Modul 1,25", "Kompaktes Profil.", teeth=16, module_size=1.25, clearance=0.25),
            v("m150", "Modul 1,50", "Standard für 0,4-mm-Düse.", teeth=16, module_size=1.50, clearance=0.25),
            v("m175", "Modul 1,75", "Robustere Zähne.", teeth=16, module_size=1.75, clearance=0.30),
            v("m200", "Modul 2,00", "Große, belastbarere Demonstratorzähne.", teeth=16, module_size=2.00, clearance=0.30),
        ],
    },
    {
        "family": 26,
        "slug": "spur-gear-pair",
        "title_de": "Stirnradpaar auf Stiftbasis",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_spur_gears",
        "principle_de": "Zwei flach gedruckte Räder laufen auf vertikalen Stiften und demonstrieren mehrere Übersetzungen.",
        "use_de": "Langsame Getriebe, Lernmodelle, Zähler und handbetätigte Mechanik.",
        "integration_de": "Achsabstand aus Modul und Zahnzahl übernehmen; Lagerung und Axialsicherung projektspezifisch ergänzen.",
        "print_de": "Räder flach, Basis flach. Zahnnaht nicht auf alle Zähne derselben Flanke legen.",
        "postprocess_de": "Zähne entgraten, Räder aufstecken und mit dünner Scheibe sichern.",
        "limitations_de": "Vereinfachte Zahnform; nicht für hohe Leistung, Drehzahl oder exakte Evolventengeometrie.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil; optional Metallachsen.",
        "part_names": ["Stiftbasis", "Rad A", "Rad B"],
        "variants": [
            v("1to1", "1:1", "Gleiche Zahnzahlen.", teeth_a=16, teeth_b=16, module_size=1.5, clearance=0.25),
            v("14to22", "14:22", "Moderate Übersetzung.", teeth_a=14, teeth_b=22, module_size=1.5, clearance=0.25),
            v("12to24", "1:2", "Deutliche Übersetzung.", teeth_a=12, teeth_b=24, module_size=1.5, clearance=0.25),
            v("10to30", "1:3", "Große Übersetzung als Demonstrator.", teeth_a=10, teeth_b=30, module_size=1.5, clearance=0.30),
        ],
    },
    {
        "family": 27,
        "slug": "rotary-detent-indexer",
        "title_de": "Dreh-Rastindexierung",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_detent_indexer",
        "principle_de": "Ein Federarm greift in Umfangskerben einer drehbaren Scheibe und erzeugt definierte Rastpositionen.",
        "use_de": "Drehwähler, Klappenpositionen, Werkzeughalter und haptische Einsteller.",
        "integration_de": "Federarm austauschbar oder zugänglich halten; Rastzahl und Scheibendurchmesser gemeinsam wählen.",
        "print_de": "Basis und Scheibe flach. Federarm in Layer-Ebene.",
        "postprocess_de": "Scheibe aufstecken und Federkraft durch behutsames Einfahren beurteilen.",
        "limitations_de": "Gedruckte Feder kann kriechen; keine sichere Verriegelung gegen hohe Momente.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Basis mit Rastfeder", "Rastscheibe"],
        "variants": [
            v("n8", "8 Positionen", "Große Rastabstände.", notches=8, beam_t=1.0, clearance=0.25),
            v("n12", "12 Positionen", "30°-Raster.", notches=12, beam_t=1.1, clearance=0.25),
            v("n16", "16 Positionen", "Feineres Raster.", notches=16, beam_t=1.2, clearance=0.25),
            v("n24", "24 Positionen", "15°-Raster mit kleinerer Kerbe.", notches=24, beam_t=1.3, clearance=0.30),
        ],
    },
    {
        "family": 28,
        "slug": "split-shaft-coupler",
        "title_de": "Geteilte Wellen-Klemmkupplung",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_shaft_coupler",
        "principle_de": "Zwei verschraubte Halbschalen klemmen zwei koaxiale Rundwellen in einer gemeinsamen Bohrung.",
        "use_de": "Langsame Modellbauwellen, Handantriebe, Teststände und provisorische Kupplungen.",
        "integration_de": "Wellen fluchten lassen und Schraubkräfte über ausreichend große Flansche einleiten.",
        "print_de": "Halbschalen mit Mulde nach oben; Testwellen stehend.",
        "postprocess_de": "Mit zwei M3-Schrauben gleichmäßig klemmen und Rundlauf prüfen.",
        "limitations_de": "Starre Kupplung gleicht keine Fluchtfehler aus; nicht für hohe Drehzahl.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Zwei M3-Schrauben und M3-Muttern.",
        "part_names": ["Kupplungshälfte A", "Kupplungshälfte B", "Testwelle A", "Testwelle B"],
        "variants": [
            v("d4", "4-mm-Welle", "Kleine Modellwellen.", bore_d=4, clearance=0.15, screw_d=3.4, nut_flat=5.7),
            v("d5", "5-mm-Welle", "Häufige Motorwelle.", bore_d=5, clearance=0.18, screw_d=3.4, nut_flat=5.7),
            v("d6", "6-mm-Welle", "Robuster Standard.", bore_d=6, clearance=0.20, screw_d=3.4, nut_flat=5.7),
            v("d8", "8-mm-Welle", "Größere langsam laufende Welle.", bore_d=8, clearance=0.25, screw_d=3.4, nut_flat=5.7),
        ],
    },
    {
        "family": 29,
        "slug": "reusable-cable-clip",
        "title_de": "Wiederlösbarer Kabel-Schnappclip",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_cable_clip",
        "principle_de": "Eine geschlitzte C-Schale federt auf und hält ein Kabel quer zur Montageplatte.",
        "use_de": "Kabelmanagement, Schläuche ohne Druck, Sensorleitungen und Bowdenzugführung.",
        "integration_de": "Montageplatte durch Gehäusewand ersetzen; Öffnung in der gewünschten Entnahmerichtung ausrichten.",
        "print_de": "Wie geliefert flach; Clipbogen in Layer-Ebene. PETG/PA für Wiederholzyklen.",
        "postprocess_de": "Kanten entgraten und Kabel seitlich von oben einklicken.",
        "limitations_de": "Nicht für heiße Leitungen, Druckschläuche oder elektrische Isolation zertifiziert.",
        "materials": ["PETG", "PA", "PP", "PLA"],
        "hardware": "Kein Fremdteil.",
        "part_names": ["Kabelclip"],
        "variants": [
            v("d4", "Kabel 4 mm", "Kompakter Leitungsclip.", cable_d=4, clearance=0.25, wall=1.8),
            v("d6", "Kabel 6 mm", "Allgemeiner Standard.", cable_d=6, clearance=0.30, wall=2.0),
            v("d8", "Kabel 8 mm", "Kräftiger Clip.", cable_d=8, clearance=0.35, wall=2.2),
            v("d10", "Kabel 10 mm", "Für dicke Leitung oder kleinen Schlauch.", cable_d=10, clearance=0.40, wall=2.4),
        ],
    },
    {
        "family": 30,
        "slug": "pulley-block",
        "title_de": "Umlenkrollen-Block",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_pulley_block",
        "principle_de": "Eine profilierte Rolle dreht zwischen zwei Wangen auf einem herausnehmbaren Stift.",
        "use_de": "Seilumlenkung, leichte Flaschenzüge, Modellbau und Kabelführung.",
        "integration_de": "Bracket an tragende Geometrie anbinden; Seilaustritt und Befestigungsloch auf Lastpfad ausrichten.",
        "print_de": "Bracket flach, Rolle und Stift stehend. Rollenrille mit kleiner Schichthöhe drucken.",
        "postprocess_de": "Rolle einsetzen, Stift durchschieben und gegen Herausfallen sichern.",
        "limitations_de": "Nicht für Personenlasten, Klettern oder sicherheitskritische Hebezeuge.",
        "materials": ["PLA", "PETG", "PA"],
        "hardware": "Kein Fremdteil; optional Metallachse.",
        "part_names": ["Rollenbügel", "Rolle", "Stift"],
        "variants": [
            v("small", "24 mm / Seil 2 mm", "Kleine Modellumlenkung.", rope_d=2, outer_d=24, pin_d=4, clearance=0.25),
            v("medium", "28 mm / Seil 3 mm", "Allgemeiner Standard.", rope_d=3, outer_d=28, pin_d=4, clearance=0.25),
            v("large", "34 mm / Seil 4 mm", "Größere Rille und Rolle.", rope_d=4, outer_d=34, pin_d=5, clearance=0.30),
            v("xlarge", "40 mm / Seil 5 mm", "Großer Demonstrator.", rope_d=5, outer_d=40, pin_d=5, clearance=0.35),
        ],
    },
    {
        "family": 31,
        "slug": "radial-o-ring-shaft-gland",
        "title_de": "Radiale O-Ring-Wellendichtung",
        "category": "09_sealing_and_service",
        "category_de": "Dicht- und Serviceschnittstellen",
        "module": "sample_radial_shaft_gland",
        "principle_de": "Ein gefetteter O-Ring sitzt radial zwischen rotierender Welle und gedrucktem Gehäuse; ein separater Haltering hält ihn axial in der Tasche.",
        "use_de": "Langsam laufende Modellwellen, Rührer, kleine Pumpen und wassergeschützte Spielzeugantriebe.",
        "integration_de": "Wellenachse exakt übernehmen, O-Ring-Datenblatt als Autorität verwenden und Haltering zugänglich halten. Fettreservoir und Einführfase nicht entfernen.",
        "print_de": "Gehäuse, Haltering und Wellenlehre stehend. Dichtflächen mit kleiner Schichthöhe und fünf Außenlinien drucken.",
        "postprocess_de": "Bohrung entgraten, O-Ring gefettet einsetzen, Haltering montieren und erst von Hand drehen.",
        "limitations_de": "Nur für niedrige Drehzahl und geringe Eintauchtiefe. Digitale Geometrie beweist weder Dichtheit noch Erwärmung oder Lebensdauer.",
        "claim_disclaimer_de": "Dichtungsgeometrie und O-Ring-Vorspannung sind nur Konstruktionsabsicht. Keine geprüfte Leckrate, IP-/Wasserdichtheit, Druckfreigabe oder Lebensdauer.",
        "materials": ["PETG", "ASA", "PA", "PLA"],
        "hardware": "Passender metrischer O-Ring und reale Metallwelle; silikonverträgliches Fett.",
        "part_names": ["Dichtungsgehäuse", "Haltering", "Wellenlehre"],
        "variants": [
            v("d2", "Welle 2 mm", "Kleine Sensor- und Spielzeugwelle.", shaft_d=2, oring_id=2, oring_cs=1.5, radial_squeeze=0.12, clearance=0.18, land_l=10, lead_in=1.0, grease_reservoir=1.2, wall=3),
            v("d3", "Welle 3 mm", "Häufige Modellmotorwelle.", shaft_d=3, oring_id=3, oring_cs=1.5, radial_squeeze=0.13, clearance=0.20, land_l=10, lead_in=1.1, grease_reservoir=1.2, wall=3),
            v("d4", "Welle 4 mm", "Robustere Modellwelle.", shaft_d=4, oring_id=4, oring_cs=1.5, radial_squeeze=0.15, clearance=0.22, land_l=11, lead_in=1.2, grease_reservoir=1.4, wall=3),
            v("d5", "Welle 5 mm", "Größere langsam laufende Welle.", shaft_d=5, oring_id=5, oring_cs=2.0, radial_squeeze=0.13, clearance=0.25, land_l=12, lead_in=1.4, grease_reservoir=1.6, wall=3.2),
        ],
    },
    {
        "family": 32,
        "slug": "o-ring-ramped-bayonet",
        "title_de": "O-Ring-vorgespanntes Rampenbajonett",
        "category": "09_sealing_and_service",
        "category_de": "Dicht- und Serviceschnittstellen",
        "module": "sample_ramped_bayonet",
        "principle_de": "Bajonettnasen laufen nach axialer Einführung über steigende Kanäle bis zu einem Hartanschlag; eine separate Nut stellt nominelle radiale O-Ring-Kompression bereit.",
        "use_de": "Wartungsdeckel, Filtergehäuse, Sensoradapter und spritzwassergeschützte Elektronikkapseln.",
        "integration_de": "O-Ring-Nut, Rampenhöhe, Axialanschlag und Laufspiel gekoppelt halten. Reale O-Ring-Schnur und Dichtflächen messen.",
        "print_de": "Stehend mit 0,2-mm- oder kleinerer Schichthöhe; Rampen und Kanäle ohne Support drucken und sauber entgraten.",
        "postprocess_de": "O-Ring fetten, axial einführen, über die Rampe drehen und Schließmoment sowie Anschlag prüfen.",
        "limitations_de": "Keine Druckbehälterfreigabe. Höhere Kompression steigert Schließmoment, Verschleiß und Risiko für O-Ring-Extrusion.",
        "claim_disclaimer_de": "O-Ring-Nut, Rampenvorspannung und Spritzwasserschutz sind nur Konstruktionsabsicht. Keine geprüfte Leckrate, IP-/Wasserdichtheit, Druckfreigabe oder Lebensdauer.",
        "materials": ["PETG", "ASA", "PA", "PLA"],
        "hardware": "O-Ring 2 mm Schnurstärke, passend zum Referenzdurchmesser.",
        "part_names": ["Rampen-Bajonettbuchse", "O-Ring-Bajonettstecker"],
        "variants": [
            v("c10", "10 % radiale Kompression", "Leichtes Schließen, geringe Dichtpressung.", core_d=24, running_clearance=0.30, lug_w=6, ramp_h=0.55, turn_deg=42, oring_id=21, oring_cs=2, radial_squeeze=0.10, hard_stop=1.5),
            v("c15", "15 % radiale Kompression", "Moderater Startwert.", core_d=24, running_clearance=0.30, lug_w=6, ramp_h=0.65, turn_deg=42, oring_id=21, oring_cs=2, radial_squeeze=0.15, hard_stop=1.5),
            v("c20", "20 % radiale Kompression", "Kräftigere radiale Dichtpressung.", core_d=24, running_clearance=0.30, lug_w=6, ramp_h=0.75, turn_deg=42, oring_id=21, oring_cs=2, radial_squeeze=0.20, hard_stop=1.5),
            v("c25", "25 % radiale Kompression", "Nur nach Drehmoment-, Extrusions- und Verschleißtest.", core_d=24, running_clearance=0.35, lug_w=6, ramp_h=0.85, turn_deg=42, oring_id=21, oring_cs=2, radial_squeeze=0.25, hard_stop=1.5),
        ],
    },
    {
        "family": 33,
        "slug": "compact-asymmetric-shaft-coupler",
        "title_de": "Kompakte asymmetrische Wellenkupplung",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_micro_shaft_coupler",
        "principle_de": "Ein geschlitzter Klemmkörper verbindet zwei koaxiale Wellen mit unabhängig dimensionierten Bohrungen und zwei M2-Klemmpunkten.",
        "use_de": "Kleine Getriebemotoren, Modellbauachsen, Kurbeln und langsame Prüfaufbauten.",
        "integration_de": "Eingangs- und Ausgangsbohrung getrennt parametrieren, axiale Überdeckung erhalten und Wellen vor dem Klemmen fluchten.",
        "print_de": "Kupplung stehend; Wellenlehren stehend. Schlitz frei von Stringing halten, fünf Außenlinien verwenden.",
        "postprocess_de": "Wellen trocken einführen, Rundlauf prüfen und beide M2-Klemmen gleichmäßig anziehen.",
        "limitations_de": "Starre Niedrigdrehzahlkupplung; gleicht keinen Fluchtfehler aus. Reibschluss und Berstfestigkeit müssen physisch geprüft werden.",
        "materials": ["PETG", "PA", "ASA", "PLA"],
        "hardware": "Zwei M2-Schrauben und Muttern beziehungsweise Inserts; reale Eingangs- und Ausgangswelle.",
        "part_names": ["Kupplungskörper", "Eingangswellenlehre", "Ausgangswellenlehre"],
        "variants": [
            v("2to3", "2 auf 3 mm", "Kleine Motor- auf Modellwelle.", input_d=2, output_d=3, input_clearance=0.15, output_clearance=0.15, length=16, outer_d=11, fastener=2.4, axial_stop=0.8),
            v("3to3", "3 auf 3 mm", "Kompakte gleichgroße Verbindung.", input_d=3, output_d=3, input_clearance=0.15, output_clearance=0.15, length=16, outer_d=11, fastener=2.4, axial_stop=0.8),
            v("3to4", "3 auf 4 mm", "Häufige Modellbaukombination.", input_d=3, output_d=4, input_clearance=0.16, output_clearance=0.18, length=18, outer_d=12, fastener=2.4, axial_stop=0.8),
            v("3to5", "3 auf 5 mm", "Größere Ausgangswelle.", input_d=3, output_d=5, input_clearance=0.18, output_clearance=0.20, length=20, outer_d=14, fastener=2.4, axial_stop=1.0),
        ],
    },
    {
        "family": 34,
        "slug": "crank-slotted-rocker-oscillator",
        "title_de": "Kurbel-Langloch-Schwinge",
        "category": "08_drives_and_components",
        "category_de": "Antriebe und weitere Mechanik",
        "module": "sample_crank_rocker",
        "principle_de": "Ein Kurbelzapfen läuft in einem Langloch und wandelt kontinuierliche Drehung in eine begrenzte Schwingbewegung um.",
        "use_de": "Flossen, Pumpen, Automaten, Rührer und langsam oszillierende Modellmechanik.",
        "integration_de": "Kurbelradius, Achsabstand, Langlochlänge und Zapfenspiel gekoppelt halten; vollständigen Schwenkraum freihalten.",
        "print_de": "Basis, Kurbel und Schwinge flach. Zapfen mit fünf Außenlinien, Kontaktflächen fein drucken.",
        "postprocess_de": "Aufstecken, Langloch leicht fetten, von Hand durchdrehen und erst dann motorisch betreiben.",
        "limitations_de": "Gleitpaarung erzeugt Spiel und Verschleiß; nicht für hohe Drehzahl oder präzise sinusförmige Bewegung.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil; optional Metallachsen oder verschleißfester Zapfen.",
        "part_names": ["Stiftbasis", "Kurbel mit Zapfen", "Langlochschwinge"],
        "variants": [
            v("r3", "Kurbelradius 3 mm", "Kleiner Hub.", crank_r=3, pivot_offset=16, slot_w=5.2, pin_d=4, rocker_r=22, plate_t=3),
            v("r4", "Kurbelradius 4 mm", "Kompakter Standardhub.", crank_r=4, pivot_offset=18, slot_w=5.4, pin_d=4, rocker_r=24, plate_t=3),
            v("r6", "Kurbelradius 6 mm", "Deutlicher Flossen- oder Pumpenhub.", crank_r=6, pivot_offset=20, slot_w=5.8, pin_d=4, rocker_r=26, plate_t=3.2),
            v("r8", "Kurbelradius 8 mm", "Großer Hub, erhöhtes Seitenmoment.", crank_r=8, pivot_offset=24, slot_w=6.2, pin_d=4, rocker_r=30, plate_t=3.4),
        ],
    },
    {
        "family": 35,
        "slug": "dual-o-ring-friction-piston",
        "title_de": "Doppel-O-Ring-Reibkolben",
        "category": "09_sealing_and_service",
        "category_de": "Dicht- und Serviceschnittstellen",
        "module": "sample_friction_piston",
        "principle_de": "Ein Kolbenkopf mit zwei beabstandeten O-Ring-Nuten läuft in einer glatten Bohrung; ein Haltering hält den schmaleren Schaft captive.",
        "use_de": "Trimmblasen, Volumenversteller, Dosierer, Dämpfer und Niederdruck-Demonstratoren.",
        "integration_de": "Bohrung, Nut, Schnurstärke und Einführfase gemeinsam auslegen; Haltering und Anschläge servicefähig halten.",
        "print_de": "Gehäuse, Kolben und Haltering stehend. Dichtflächen fein und mit mindestens fünf Außenlinien drucken.",
        "postprocess_de": "Nuten entgraten, O-Ringe fetten, Kolben gerade einsetzen und Schubkraft über den ganzen Weg messen.",
        "limitations_de": "Kein Druckzylinder. Reibung, Kriechen und Leckage hängen stark von realem O-Ring und Oberflächenqualität ab.",
        "claim_disclaimer_de": "Kolben- und O-Ring-Geometrie sind nur Konstruktionsabsicht. Keine geprüfte Leckrate, IP-/Wasserdichtheit, Druckfreigabe oder Lebensdauer.",
        "materials": ["PETG", "ASA", "PA", "PLA"],
        "hardware": "Zwei passende O-Ringe; silikonverträgliches Fett.",
        "part_names": ["Kolbengehäuse", "Doppel-O-Ring-Kolben", "Haltering"],
        "variants": [
            v("d12", "Bohrung 12 mm", "Kompakter Volumenversteller.", bore_d=12, travel=20, oring_id=9.5, oring_cs=1.5, groove_depth=1.08, groove_spacing=4.4, lead_in=1.0, anti_loss_stop=4.0, clearance=0.20),
            v("d16", "Bohrung 16 mm", "Kleine Trimm- oder Dosierkammer.", bore_d=16, travel=22, oring_id=13.5, oring_cs=1.5, groove_depth=1.08, groove_spacing=4.4, lead_in=1.1, anti_loss_stop=4.0, clearance=0.20),
            v("d20", "Bohrung 20 mm", "Allgemeiner Standard.", bore_d=20, travel=24, oring_id=17.5, oring_cs=1.5, groove_depth=1.08, groove_spacing=4.4, lead_in=1.2, anti_loss_stop=4.5, clearance=0.22),
            v("d24", "Bohrung 24 mm", "Größerer Stellbereich.", bore_d=24, travel=26, oring_id=20.5, oring_cs=2.0, groove_depth=1.44, groove_spacing=5.2, lead_in=1.4, anti_loss_stop=5.0, clearance=0.25),
        ],
    },
    {
        "family": 36,
        "slug": "captive-service-hinge-pin",
        "title_de": "Captiver servicefähiger Gelenkstift",
        "category": "01_rotation_1d",
        "category_de": "Eindimensionale Drehbewegung",
        "module": "sample_captive_hinge_pin",
        "principle_de": "Ein Kopfbolzen verbindet zwei Gelenkblätter; ein seitlich montierbarer C-Clip greift in eine Umfangsnut und erlaubt zerstörungsfreie Demontage.",
        "use_de": "Wartbare Klappen, Gliederkörper, Modellfahrzeuge und nasse oder schmutzige Gelenke.",
        "integration_de": "Nutdurchmesser, Clipöffnung und Griffweite gekoppelt halten; Montagezugang zur Clipseite erhalten.",
        "print_de": "Blätter flach, Stift stehend, Clip flach. Clip bevorzugt aus PETG/PA drucken.",
        "postprocess_de": "Bohrungen entgraten, Stift einschieben und Clip seitlich in die Nut drücken; Zugprüfung durchführen.",
        "limitations_de": "Gedruckter Clip kann kriechen oder bei Kälte brechen. Für hohe Last Metallstift und Norm-Sicherungsring verwenden.",
        "materials": ["PETG", "PA", "PLA"],
        "hardware": "Kein Fremdteil; optional Metallstift und Norm-Sicherungsring.",
        "part_names": ["Gelenkblatt A", "Gelenkblatt B", "Nutstift", "C-Clip"],
        "variants": [
            v("d2", "Stift 2 mm", "Sehr leichte Kleingelenke.", pin_d=2, bearing_clearance=0.20, head_d=5, retainer_clearance=0.20, grip_l=12, leaf_l=24),
            v("d3", "Stift 3 mm", "Kompakte Modellmechanik.", pin_d=3, bearing_clearance=0.22, head_d=6, retainer_clearance=0.22, grip_l=13, leaf_l=26),
            v("d4", "Stift 4 mm", "Allgemeiner Standard.", pin_d=4, bearing_clearance=0.25, head_d=7, retainer_clearance=0.25, grip_l=13, leaf_l=28),
            v("d5", "Stift 5 mm", "Robusteres Wartungsgelenk.", pin_d=5, bearing_clearance=0.30, head_d=8, retainer_clearance=0.30, grip_l=14, leaf_l=30),
        ],
    },
    {
        "family": 37,
        "slug": "compression-cable-gland",
        "title_de": "Kompressions-Kabeldurchführung",
        "category": "09_sealing_and_service",
        "category_de": "Dicht- und Serviceschnittstellen",
        "module": "sample_cable_gland",
        "principle_de": "Eine Gewindemutter presst einen geschlitzten Elastomerring axial um ein Kabel; das Gehäuse übernimmt Wandanschluss und Zugpfad.",
        "use_de": "Sensorleitungen, Kleinspannungskabel und vergossene Durchführungen in Gehäusen.",
        "integration_de": "Kabelmantel messen, Zugentlastung getrennt vorsehen und Dicht-/Pottingmaterial auf Verträglichkeit prüfen.",
        "print_de": "Gehäuse, Mutter und Ring stehend. Gewinde mit kleiner Schichthöhe; Ring nur als TPU-Lehre betrachten.",
        "postprocess_de": "Gewinde einlaufen lassen, Kabel und Ring einsetzen, Mutter gleichmäßig anziehen und Zug-/Lecktest durchführen.",
        "limitations_de": "Nicht für Netzspannung, Druckleitungen oder zertifizierte IP-Schutzarten. Gedruckter Ring ersetzt keinen qualifizierten Dichteinsatz.",
        "claim_disclaimer_de": "Die Durchführung ist nur die Konstruktionsabsicht eines unqualifizierten Dicht- und Montagekonzepts. Keine geprüfte Leckrate, IP-/Wasserdichtheit, Druckfreigabe, elektrische Freigabe oder Lebensdauer.",
        "materials": ["PETG", "ASA", "PA", "TPU"],
        "hardware": "Reales Kabel sowie geeigneter Elastomer- oder Pottingeinsatz; optional separate Zugentlastung.",
        "part_names": ["Gewinde-Glandkörper", "Kompressionsring-Lehre", "Glandmutter"],
        "variants": [
            v("d2", "Kabel 2 mm", "Dünne Sensorleitung.", cable_d=2, seal_clearance=0.25, compression_l=4.0, thread_d=12, pitch=2.5, strain_relief=10, wall=3),
            v("d3", "Kabel 3 mm", "Kleine Kleinspannungsleitung.", cable_d=3, seal_clearance=0.30, compression_l=4.5, thread_d=16, pitch=3.0, strain_relief=12, wall=3),
            v("d4", "Kabel 4 mm", "Allgemeiner Standard.", cable_d=4, seal_clearance=0.30, compression_l=5.0, thread_d=16, pitch=3.0, strain_relief=14, wall=3),
            v("d6", "Kabel 6 mm", "Kräftigere Leitung.", cable_d=6, seal_clearance=0.40, compression_l=6.0, thread_d=20, pitch=4.0, strain_relief=16, wall=3.2),
        ],
    },
    {
        "family": 38,
        "slug": "cylindrical-cell-cradle",
        "title_de": "Zylindrischer Zellhalter",
        "category": "10_component_fixtures",
        "category_de": "Komponentenhalter",
        "module": "sample_cell_cradle",
        "principle_de": "Offene zylindrische Sättel führen Batteriezellen; Querfenster nehmen einen separaten Gurt auf und halten elektrische Kontaktzonen frei.",
        "use_de": "Batteriefächer, Prototypen, Messgeräte und Modellbau-Elektronik.",
        "integration_de": "Reale Zellen messen, Kontakt- und Isolations-Keep-outs erhalten und Halter an eine tragende, temperaturverträgliche Wand anbinden.",
        "print_de": "Halter flach, Durchmesserlehre stehend. Gurtfenster und Satteloberflächen ohne Support drucken.",
        "postprocess_de": "Kanten brechen, Lehre prüfen, dann echte Zelle ohne Kraft einsetzen und mit nichtleitendem Gurt sichern.",
        "limitations_de": "Keine elektrischen Kontakte oder Batteriesicherheitsfunktion. Zellhüllen dürfen nicht gequetscht, geritzt oder erwärmt werden.",
        "materials": ["PETG", "ASA", "PA", "PLA"],
        "hardware": "Reale Zelle, nichtleitender Gurt und supplier-spezifische elektrische Kontakte.",
        "part_names": ["Zellhalter", "Durchmesserlehre"],
        "variants": [
            v("aaa1", "1 x AAA", "Einzelne AAA-Zelle.", cell_d=10.5, cell_l=44.5, count=1, cell_gap=2, clearance=0.35, strap_w=6, contact_keepout=5),
            v("aaa2", "2 x AAA", "Zwei parallele AAA-Zellen.", cell_d=10.5, cell_l=44.5, count=2, cell_gap=2, clearance=0.35, strap_w=6, contact_keepout=5),
            v("aa1", "1 x AA", "Einzelne AA-Zelle.", cell_d=14.5, cell_l=50.5, count=1, cell_gap=2, clearance=0.40, strap_w=8, contact_keepout=6),
            v("18650", "1 x 18650", "Nur gegen gemessene reale Zelle verwenden.", cell_d=18.6, cell_l=65, count=1, cell_gap=2, clearance=0.45, strap_w=10, contact_keepout=8),
        ],
    },
    {
        "family": 39,
        "slug": "sealed-magnetic-actuator-pocket",
        "title_de": "Abgedichtete Magnetbetätiger-Tasche",
        "category": "10_component_fixtures",
        "category_de": "Komponentenhalter",
        "module": "sample_magnetic_actuator",
        "principle_de": "Ein externer Magnetschieber läuft über einer ununterbrochenen Wandbarriere ohne Sensordurchbruch; dahinter liegt ein supplier-spezifischer Reed- oder Hall-Sensor-Keep-out. Diese Barriere ist nicht auf Dichtheit geprüft.",
        "use_de": "Magnetisch durch eine ununterbrochene Wand betätigte Schalterkonzepte, abnehmbare Magnetschlüssel und Sensortrigger; wassernahe Elektronik nur nach eigener Dichtheitsprüfung.",
        "integration_de": "Magnet und Sensor als gekaufte Komponenten vermessen, Polung festlegen und Wanddicke nur nach Reichweitentest wählen.",
        "print_de": "Gehäuse flach mit kurzer Brücke über der Sensortasche; Schieber flach. Magnettasche sauber halten.",
        "postprocess_de": "Magnet einsetzen/sichern, Sensor hinter der Wand positionieren und Schaltabstand in allen Orientierungen messen.",
        "limitations_de": "Keine garantierte Schaltfunktion ohne reale Magnet-/Sensordaten. Fremdmagnete und Vibration können Fehlauslösung verursachen. „Abgedichtet“ beziehungsweise „dicht“ bezeichnet hier nur die nicht durchdrungene Wandbarriere, nicht eine geprüfte Dichtheit.",
        "claim_disclaimer_de": "„Abgedichtet“ und „dicht“ bezeichnen ausschließlich die Konstruktionsabsicht einer ununterbrochenen Wandbarriere ohne Sensordurchbruch. Keine geprüfte Leckrate, IP-/Wasserdichtheit, Druckfreigabe oder Lebensdauer.",
        "materials": ["PETG", "ASA", "PA", "PLA"],
        "hardware": "Neodym-Magnet etwa 6 x 3 mm und supplier-spezifischer Reed- oder Hall-Sensor.",
        "part_names": ["Dichte Sensortasche mit Führung", "Magnetschieber"],
        "variants": [
            v("wall1", "Wand 1 mm", "Große Reichweite, geringe mechanische Reserve.", wall_t=1, magnet_d=6, magnet_l=3, switch_keepout=[18,6,6], travel=20, retention=1.2, clearance=0.35),
            v("wall2", "Wand 2 mm", "Ausgewogener Startwert.", wall_t=2, magnet_d=6, magnet_l=3, switch_keepout=[18,6,6], travel=20, retention=1.2, clearance=0.35),
            v("wall3", "Wand 3 mm", "Robustere Barriere, stärkeren Magnet prüfen.", wall_t=3, magnet_d=6, magnet_l=3, switch_keepout=[18,6,6], travel=22, retention=1.4, clearance=0.40),
            v("wall4", "Wand 4 mm", "Nur nach Reichweitentest.", wall_t=4, magnet_d=6, magnet_l=3, switch_keepout=[18,6,6], travel=24, retention=1.6, clearance=0.45),
        ],
    },
]

assert len(FAMILIES) == 39
assert sum(len(f["variants"]) for f in FAMILIES) == 156
