#!/usr/bin/env python3
"""Generate ZEN KINTSUGI WAVE FIFO revision 3.0.0.

The production model is deterministic and fully parametric. Functional solids
are CadQuery/OpenCascade B-Reps. Decorative waves and kintsugi paths are sparse
analytic spline ribbons converted directly to B-Rep cutters and inlays. No
image-to-3D mesh, raster displacement, GLB, OBJ, or STL is used as source.

All exports generated by this script are DRAFT validation artifacts until the
physical, wall-mount, watermark, and final-release gates in design-spec.yaml
are complete.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import sys
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence
from xml.etree import ElementTree as ET

import cadquery as cq
import numpy as np
import trimesh
import yaml
from shapely.geometry import MultiPolygon, Polygon, box

from procedural_profiles import (
    crown_ribbons,
    front_rail_profile,
    rounded_rectangle,
    side_frame_profile,
    skin_kintsugi_network,
    skin_outline,
    skin_wave_grooves,
)


VERSION = "3.0.0"
GEOMETRY_REVISION = "r3.0.0-candidate-02"


@dataclass(frozen=True)
class Params:
    maximum_roll_diameter: float
    maximum_roll_width: float
    gauge_diameter: float
    gauge_width: float
    shaft_clear_width: float
    shaft_clear_depth: float
    rear_clearance: float
    front_clearance: float
    outer_width: float
    total_depth: float
    back_thickness: float
    side_frame_thickness: float
    front_thickness: float
    bottom_height: float
    middle_height: float
    top_height: float
    crown_height: float
    rail_center_x: float
    rail_width: float
    rail_height: float
    joint_hole_diameter: float
    joint_pad_diameter: float
    joint_pad_thickness: float
    alignment_boss_diameter: float
    alignment_boss_height: float
    alignment_recess_diameter: float
    alignment_recess_depth: float
    joint_axis_x: tuple[float, float]
    joint_axis_y: tuple[float, float]
    wall_axis_x: tuple[float, float]
    wall_lower_z: float
    wall_upper_from_top: float
    wall_hole_diameter: float
    wall_counterbore_diameter: float
    wall_counterbore_depth: float
    wall_boss_depth: float
    skin_thickness: float
    skin_margin: float
    wave_groove_width: float
    wave_groove_depth: float
    gold_groove_depth: float
    gold_width: float
    gold_proud: float
    nozzle: float
    line_width: float
    structural_layer_height: float
    decorative_layer_height: float
    tessellation_tolerance: float
    tessellation_angular_tolerance: float

    @property
    def outer_half_width(self) -> float:
        return self.outer_width / 2.0

    @property
    def roll_center_y(self) -> float:
        return self.back_thickness + self.rear_clearance + self.gauge_width / 2.0

    @property
    def front_y(self) -> float:
        return self.total_depth - self.front_thickness

    @property
    def total_body_height(self) -> float:
        return self.bottom_height + self.middle_height + self.top_height

    @property
    def output_rest_center_z(self) -> float:
        radius = self.gauge_diameter / 2.0
        rail_inner = self.rail_center_x - self.rail_width / 2.0
        return self.rail_height + math.sqrt(radius**2 - rail_inner**2)


@dataclass
class Part:
    name: str
    assembly_shape: cq.Shape
    print_shape: cq.Shape
    material: str
    quantity: int = 1
    notes: str = ""


@dataclass
class BuildResult:
    params: Params
    parts: list[Part]
    assembly_shapes: dict[str, cq.Shape]
    coupons: list[Part]


def load_params(spec_path: Path) -> Params:
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    pp = spec["production_parameters"]
    roll = pp["roll"]
    body = pp["body"]
    stop = pp["output_stop"]
    joint = pp["module_joint"]
    mount = pp["wall_mount"]
    skin = pp["decorative_skin"]
    process = pp["process"]
    params = Params(
        maximum_roll_diameter=float(roll["maximum_diameter_mm"]),
        maximum_roll_width=float(roll["maximum_width_mm"]),
        gauge_diameter=float(roll["gauge_diameter_mm"]),
        gauge_width=float(roll["gauge_width_mm"]),
        shaft_clear_width=float(roll["shaft_clear_width_mm"]),
        shaft_clear_depth=float(roll["shaft_clear_depth_mm"]),
        rear_clearance=float(roll["rear_clearance_mm"]),
        front_clearance=float(roll["front_clearance_mm"]),
        outer_width=float(body["outer_width_mm"]),
        total_depth=float(body["total_depth_mm"]),
        back_thickness=float(body["back_thickness_mm"]),
        side_frame_thickness=float(body["side_frame_thickness_mm"]),
        front_thickness=float(body["front_thickness_mm"]),
        bottom_height=float(body["bottom_module_height_mm"]),
        middle_height=float(body["middle_module_height_mm"]),
        top_height=float(body["top_module_height_mm"]),
        crown_height=float(body["optional_crown_height_mm"]),
        rail_center_x=float(stop["rail_center_x_mm"]),
        rail_width=float(stop["rail_width_mm"]),
        rail_height=float(stop["rail_height_mm"]),
        joint_hole_diameter=float(joint["hole_diameter_mm"]),
        joint_pad_diameter=float(joint["pad_diameter_mm"]),
        joint_pad_thickness=float(joint["pad_thickness_mm"]),
        alignment_boss_diameter=float(joint["alignment_boss_diameter_mm"]),
        alignment_boss_height=float(joint["alignment_boss_height_mm"]),
        alignment_recess_diameter=float(joint["alignment_recess_diameter_mm"]),
        alignment_recess_depth=float(joint["alignment_recess_depth_mm"]),
        joint_axis_x=tuple(float(value) for value in joint["axis_x_mm"]),
        joint_axis_y=tuple(float(value) for value in joint["axis_y_mm"]),
        wall_axis_x=tuple(float(value) for value in mount["axis_x_mm"]),
        wall_lower_z=float(mount["lower_axis_z_mm"]),
        wall_upper_from_top=float(mount["upper_axis_z_from_top_mm"]),
        wall_hole_diameter=float(mount["through_hole_diameter_mm"]),
        wall_counterbore_diameter=float(mount["head_counterbore_diameter_mm"]),
        wall_counterbore_depth=float(mount["head_counterbore_depth_mm"]),
        wall_boss_depth=float(mount["local_boss_depth_mm"]),
        skin_thickness=float(skin["base_thickness_mm"]),
        skin_margin=float(skin["edge_margin_mm"]),
        wave_groove_width=float(skin["wave_groove_width_mm"]),
        wave_groove_depth=float(skin["wave_groove_depth_mm"]),
        gold_groove_depth=float(skin["gold_groove_depth_mm"]),
        gold_width=float(skin["gold_width_mm"]),
        gold_proud=float(skin["gold_proud_mm"]),
        nozzle=float(process["nozzle_mm"]),
        line_width=float(process["line_width_mm"]),
        structural_layer_height=float(process["structural_layer_height_mm"]),
        decorative_layer_height=float(process["decorative_layer_height_mm"]),
        tessellation_tolerance=float(process["tessellation_tolerance_mm"]),
        tessellation_angular_tolerance=float(process["tessellation_angular_tolerance_rad"]),
    )
    validate_params(params)
    return params


def validate_params(p: Params) -> None:
    if p.outer_width > 150.0 or p.total_depth > 130.0 or p.total_body_height > 680.0:
        raise ValueError("Approved body envelope exceeded")
    if max(p.bottom_height, p.middle_height, p.top_height) > 260.0:
        raise ValueError("Approved module-height limit exceeded")
    if p.outer_width <= p.shaft_clear_width:
        raise ValueError("Outer width must exceed clear shaft width")
    expected_depth = (
        p.back_thickness
        + p.rear_clearance
        + p.gauge_width
        + p.front_clearance
        + p.front_thickness
    )
    if abs(expected_depth - p.total_depth) > 0.25:
        raise ValueError(f"Depth stack mismatch: {expected_depth:.3f} != {p.total_depth:.3f}")
    if p.skin_thickness - p.gold_groove_depth < 2.0 * p.structural_layer_height:
        raise ValueError("Decorative skin reserve below two structural layers")


def _polygon_parts(geometry) -> list[Polygon]:
    if geometry.is_empty:
        return []
    if isinstance(geometry, Polygon):
        return [geometry]
    if isinstance(geometry, MultiPolygon):
        return [poly for poly in geometry.geoms if poly.area > 1e-5]
    parts = []
    for item in getattr(geometry, "geoms", []):
        parts.extend(_polygon_parts(item))
    return parts


def _wire_from_ring(coords, plane: str, offset: float) -> cq.Wire:
    points = []
    for a, b in list(coords)[:-1]:
        if plane == "YZ":
            points.append(cq.Vector(offset, float(a), float(b)))
        elif plane == "XZ":
            points.append(cq.Vector(float(a), offset, float(b)))
        elif plane == "XY":
            points.append(cq.Vector(float(a), float(b), offset))
        else:
            raise ValueError(plane)
    return cq.Wire.makePolygon(points, close=True)


def extrude_geometry(geometry, plane: str, offset: float, thickness: float) -> cq.Shape:
    """Extrude Shapely polygons in one of the canonical project planes."""
    solids: list[cq.Shape] = []
    if plane == "YZ":
        vector = cq.Vector(thickness, 0.0, 0.0)
    elif plane == "XZ":
        vector = cq.Vector(0.0, thickness, 0.0)
    elif plane == "XY":
        vector = cq.Vector(0.0, 0.0, thickness)
    else:
        raise ValueError(plane)
    for polygon in _polygon_parts(geometry):
        outer = _wire_from_ring(polygon.exterior.coords, plane, offset)
        inners = [_wire_from_ring(ring.coords, plane, offset) for ring in polygon.interiors]
        solids.append(cq.Solid.extrudeLinear(outer, inners, vector))
    if not solids:
        raise ValueError("Cannot extrude empty geometry")
    if len(solids) == 1:
        return solids[0]
    return cq.Compound.makeCompound(solids)


def make_box(x0: float, y0: float, z0: float, dx: float, dy: float, dz: float) -> cq.Shape:
    return cq.Solid.makeBox(dx, dy, dz, cq.Vector(x0, y0, z0))


def cylinder(
    radius: float,
    height: float,
    base: tuple[float, float, float],
    direction: tuple[float, float, float],
) -> cq.Shape:
    return cq.Solid.makeCylinder(radius, height, cq.Vector(*base), cq.Vector(*direction))


def fuse_all(shapes: Iterable[cq.Shape]) -> cq.Shape:
    items = [shape for shape in shapes if shape is not None]
    if not items:
        raise ValueError("No shapes to fuse")
    result = items[0]
    for item in items[1:]:
        result = result.fuse(item)
    return result


def cut_all(base: cq.Shape, cutters: Iterable[cq.Shape]) -> cq.Shape:
    result = base
    for cutter in cutters:
        result = result.cut(cutter)
    return result


def module_skin_screw_centers(p: Params, height: float) -> list[tuple[float, float]]:
    return [(p.total_depth - 16.0, height * 0.28), (p.total_depth - 16.0, height * 0.72)]


def add_skin_insert_bosses(p: Params, body: cq.Shape, height: float) -> cq.Shape:
    additions = []
    cutters = []
    for y, z in module_skin_screw_centers(p, height):
        additions.append(
            cylinder(6.0, 7.0, (p.outer_half_width - 7.0, y, z), (1.0, 0.0, 0.0))
        )
        cutters.append(
            cylinder(2.3, 7.4, (p.outer_half_width - 7.2, y, z), (1.0, 0.0, 0.0))
        )
    return cut_all(fuse_all([body, *additions]), cutters)


def make_joint_features(
    p: Params,
    height: float,
    bottom_recess: bool,
    top_boss: bool,
) -> tuple[list[cq.Shape], list[cq.Shape]]:
    additions: list[cq.Shape] = []
    cutters: list[cq.Shape] = []
    pad_r = p.joint_pad_diameter / 2.0
    for x in p.joint_axis_x:
        for y in p.joint_axis_y:
            additions.append(cylinder(pad_r, p.joint_pad_thickness, (x, y, 0.0), (0.0, 0.0, 1.0)))
            additions.append(
                cylinder(
                    pad_r,
                    p.joint_pad_thickness,
                    (x, y, height - p.joint_pad_thickness),
                    (0.0, 0.0, 1.0),
                )
            )
            if top_boss:
                additions.append(
                    cylinder(
                        p.alignment_boss_diameter / 2.0,
                        p.alignment_boss_height,
                        (x, y, height),
                        (0.0, 0.0, 1.0),
                    )
                )
            cutters.append(
                cylinder(
                    p.joint_hole_diameter / 2.0,
                    height + p.alignment_boss_height + 0.4,
                    (x, y, -0.2),
                    (0.0, 0.0, 1.0),
                )
            )
            if bottom_recess:
                cutters.append(
                    cylinder(
                        p.alignment_recess_diameter / 2.0,
                        p.alignment_recess_depth + 0.1,
                        (x, y, -0.05),
                        (0.0, 0.0, 1.0),
                    )
                )
    return additions, cutters


def make_wall_mount_features(p: Params, body: cq.Shape, local_z: float) -> cq.Shape:
    additions = []
    cutters = []
    for x in p.wall_axis_x:
        additions.append(cylinder(9.0, p.wall_boss_depth, (x, 0.0, local_z), (0.0, 1.0, 0.0)))
        cutters.append(
            cylinder(
                p.wall_hole_diameter / 2.0,
                p.wall_boss_depth + 0.6,
                (x, -0.3, local_z),
                (0.0, 1.0, 0.0),
            )
        )
        cutters.append(
            cylinder(
                p.wall_counterbore_diameter / 2.0,
                p.wall_counterbore_depth + 0.2,
                (x, p.wall_boss_depth - p.wall_counterbore_depth - 0.1, local_z),
                (0.0, 1.0, 0.0),
            )
        )
    return cut_all(fuse_all([body, *additions]), cutters)


def make_module(
    p: Params,
    kind: str,
    height: float,
    phase: float,
    bottom_recess: bool,
    top_boss: bool,
    wall_mount_z: float | None,
) -> cq.Shape:
    """Build one exact functional body module in local assembly coordinates."""
    parts: list[cq.Shape] = []
    # Closed back keeps the wall side clean and supplies a continuous load path.
    parts.append(
        make_box(
            -p.outer_half_width,
            0.0,
            0.0,
            p.outer_width,
            p.back_thickness,
            height,
        )
    )
    side_profile = side_frame_profile(p.total_depth, height, phase)
    parts.append(extrude_geometry(side_profile, "YZ", -p.outer_half_width, p.side_frame_thickness))
    parts.append(
        extrude_geometry(
            side_profile,
            "YZ",
            p.outer_half_width - p.side_frame_thickness,
            p.side_frame_thickness,
        )
    )
    front_profile = front_rail_profile(
        p.outer_half_width,
        height,
        p.shaft_clear_width / 2.0,
        output_module=kind == "bottom",
    )
    parts.append(extrude_geometry(front_profile, "XZ", p.front_y, p.front_thickness))

    if kind == "bottom":
        rail_length = p.front_y - p.back_thickness + 0.5
        gauge_front_y = p.back_thickness + p.rear_clearance + p.gauge_width
        nose_clearance = 0.3
        nose_start_y = gauge_front_y + nose_clearance
        nose_length = p.front_y - nose_start_y
        if nose_length < 1.2:
            raise ValueError("Output-stop nose is too short for a printable face connection")
        for x in (-p.rail_center_x, p.rail_center_x):
            parts.append(
                make_box(
                    x - p.rail_width / 2.0,
                    p.back_thickness,
                    0.0,
                    p.rail_width,
                    rail_length,
                    p.rail_height,
                )
            )
            # A small front nose resists accidental forward release; the roll
            # is intentionally lifted before extraction and must be couponed.
            # Keep the parked rigid gauge behind the nose with a deterministic
            # axial gap; the candidate-01 nose overlapped the gauge by 4 mm.
            parts.append(
                make_box(
                    x - p.rail_width / 2.0,
                    nose_start_y,
                    p.rail_height,
                    p.rail_width,
                    nose_length,
                    4.0,
                )
            )

    body = fuse_all(parts)
    joint_additions, joint_cutters = make_joint_features(
        p, height, bottom_recess=bottom_recess, top_boss=top_boss
    )
    body = cut_all(fuse_all([body, *joint_additions]), joint_cutters)
    body = add_skin_insert_bosses(p, body, height)
    if wall_mount_z is not None:
        body = make_wall_mount_features(p, body, wall_mount_z)

    if kind == "top":
        # Optional crown sockets remain outside the gauge axial envelope.
        socket_w = 6.6
        socket_d = 4.6
        for x in (-58.0, 58.0):
            body = body.cut(
                make_box(
                    x - socket_w / 2.0,
                    p.front_y + 0.4,
                    height - 8.2,
                    socket_w,
                    socket_d,
                    8.4,
                )
            )
    return body.clean()


def make_skin(p: Params, height: float, phase: float) -> tuple[cq.Shape, cq.Shape]:
    screw_centers = module_skin_screw_centers(p, height)
    outline = skin_outline(p.total_depth, height, p.skin_margin)
    base = extrude_geometry(outline, "YZ", 0.0, p.skin_thickness)

    wave_geometry = skin_wave_grooves(
        p.total_depth,
        height,
        p.skin_margin,
        p.wave_groove_width,
        phase,
    )
    wave_cutter = extrude_geometry(
        wave_geometry,
        "YZ",
        p.skin_thickness - p.wave_groove_depth,
        p.wave_groove_depth + 0.15,
    )
    gold_geometry = skin_kintsugi_network(
        p.total_depth,
        height,
        p.skin_margin,
        p.gold_width,
        phase,
        keepout_centers=screw_centers,
    )
    gold_cutter = extrude_geometry(
        gold_geometry,
        "YZ",
        p.skin_thickness - p.gold_groove_depth,
        p.gold_groove_depth + 0.15,
    )
    skin = cut_all(base, [wave_cutter, gold_cutter])
    for y, z in screw_centers:
        skin = skin.cut(cylinder(1.7, p.skin_thickness + 0.4, (-0.2, y, z), (1.0, 0.0, 0.0)))
        skin = skin.cut(
            cylinder(
                3.25,
                0.9,
                (p.skin_thickness - 0.75, y, z),
                (1.0, 0.0, 0.0),
            )
        )

    gold = extrude_geometry(
        gold_geometry,
        "YZ",
        p.skin_thickness - p.gold_groove_depth + 0.05,
        p.gold_groove_depth + p.gold_proud - 0.05,
    )
    return skin.clean(), gold.clean()


def make_crown(p: Params) -> cq.Shape:
    profile = crown_ribbons(p.outer_width - 10.0, p.crown_height, ribbon_width=8.0)
    crown = extrude_geometry(profile, "XZ", 0.0, p.front_thickness)
    tabs = []
    for x in (-58.0, 58.0):
        tabs.append(make_box(x - 3.0, 0.5, -8.0, 6.0, 4.0, 8.0))
    return fuse_all([crown, *tabs]).clean()


def rounded_box_xy(width: float, depth: float, height: float, radius: float) -> cq.Shape:
    profile = rounded_rectangle(-width / 2.0, -depth / 2.0, width / 2.0, depth / 2.0, radius)
    return extrude_geometry(profile, "XY", 0.0, height)


def make_optional_scent_tray() -> cq.Shape:
    outer = rounded_box_xy(64.0, 52.0, 10.0, 10.0)
    inner = rounded_box_xy(56.0, 44.0, 8.0, 8.0).translate((0.0, 0.0, 4.0))
    tray = outer.cut(inner)
    key = make_box(-7.0, -4.0, -6.0, 14.0, 8.0, 6.0)
    return tray.fuse(key).clean()


def make_joint_coupon(p: Params) -> tuple[cq.Shape, cq.Shape]:
    lower = rounded_box_xy(34.0, 34.0, p.joint_pad_thickness, 4.0)
    lower = lower.fuse(
        cylinder(
            p.alignment_boss_diameter / 2.0,
            p.alignment_boss_height,
            (0.0, 0.0, p.joint_pad_thickness),
            (0.0, 0.0, 1.0),
        )
    )
    lower = lower.cut(
        cylinder(
            p.joint_hole_diameter / 2.0,
            p.joint_pad_thickness + p.alignment_boss_height + 0.2,
            (0.0, 0.0, -0.1),
            (0.0, 0.0, 1.0),
        )
    )
    upper = rounded_box_xy(34.0, 34.0, p.joint_pad_thickness, 4.0)
    upper = upper.cut(
        cylinder(
            p.alignment_recess_diameter / 2.0,
            p.alignment_recess_depth + 0.1,
            (0.0, 0.0, -0.05),
            (0.0, 0.0, 1.0),
        )
    )
    upper = upper.cut(
        cylinder(
            p.joint_hole_diameter / 2.0,
            p.joint_pad_thickness + 0.2,
            (0.0, 0.0, -0.1),
            (0.0, 0.0, 1.0),
        )
    )
    return lower.clean(), upper.clean()


def make_skin_coupon(p: Params) -> tuple[cq.Shape, cq.Shape]:
    height = 44.0
    depth = 68.0
    outline = rounded_rectangle(0.0, 0.0, depth, height, 5.0)
    base = extrude_geometry(outline, "YZ", 0.0, p.skin_thickness)
    waves = skin_wave_grooves(depth, height, 4.0, p.wave_groove_width, 0.3)
    gold_net = skin_kintsugi_network(depth, height, 4.0, p.gold_width, 0.3)
    base = base.cut(
        extrude_geometry(
            waves,
            "YZ",
            p.skin_thickness - p.wave_groove_depth,
            p.wave_groove_depth + 0.1,
        )
    )
    base = base.cut(
        extrude_geometry(
            gold_net,
            "YZ",
            p.skin_thickness - p.gold_groove_depth,
            p.gold_groove_depth + 0.1,
        )
    )
    gold = extrude_geometry(
        gold_net,
        "YZ",
        p.skin_thickness - p.gold_groove_depth + 0.05,
        p.gold_groove_depth + p.gold_proud - 0.05,
    )
    return base.clean(), gold.clean()


def shift_to_origin(shape: cq.Shape) -> cq.Shape:
    bb = shape.BoundingBox()
    return shape.translate((-bb.xmin, -bb.ymin, -bb.zmin))


def skin_print_orientation(shape: cq.Shape) -> cq.Shape:
    rotated = shape.rotate((0, 0, 0), (0, 1, 0), -90.0)
    return shift_to_origin(rotated)


def crown_print_orientation(shape: cq.Shape) -> cq.Shape:
    rotated = shape.rotate((0, 0, 0), (1, 0, 0), 90.0)
    return shift_to_origin(rotated)


def build_model(p: Params) -> BuildResult:
    bottom = make_module(
        p,
        "bottom",
        p.bottom_height,
        phase=0.2,
        bottom_recess=False,
        top_boss=True,
        wall_mount_z=p.wall_lower_z,
    )
    middle = make_module(
        p,
        "middle",
        p.middle_height,
        phase=1.2,
        bottom_recess=True,
        top_boss=True,
        wall_mount_z=None,
    )
    top = make_module(
        p,
        "top",
        p.top_height,
        phase=2.1,
        bottom_recess=True,
        top_boss=False,
        wall_mount_z=p.top_height - p.wall_upper_from_top,
    )
    skin_bottom, gold_bottom = make_skin(p, p.bottom_height, 0.2)
    skin_middle, gold_middle = make_skin(p, p.middle_height, 1.2)
    skin_top, gold_top = make_skin(p, p.top_height, 2.1)
    crown = make_crown(p)
    tray = make_optional_scent_tray()
    joint_lower, joint_upper = make_joint_coupon(p)
    skin_coupon, skin_coupon_gold = make_skin_coupon(p)

    z_middle = p.bottom_height
    z_top = p.bottom_height + p.middle_height
    # Leave a small assembly clearance while keeping the complete base model,
    # including the proud gold inlay and joint pads, inside the 150 mm envelope.
    skin_x = p.outer_half_width + 0.05
    crown_y = p.front_y
    assembly = {
        "body_bottom": bottom,
        "body_middle": middle.translate((0.0, 0.0, z_middle)),
        "body_top": top.translate((0.0, 0.0, z_top)),
        "skin_bottom": skin_bottom.translate((skin_x, 0.0, 0.0)),
        "gold_bottom": gold_bottom.translate((skin_x, 0.0, 0.0)),
        "skin_middle": skin_middle.translate((skin_x, 0.0, z_middle)),
        "gold_middle": gold_middle.translate((skin_x, 0.0, z_middle)),
        "skin_top": skin_top.translate((skin_x, 0.0, z_top)),
        "gold_top": gold_top.translate((skin_x, 0.0, z_top)),
        "crown_optional": crown.translate((0.0, crown_y, p.total_body_height)),
    }
    parts = [
        Part("body_bottom", bottom, shift_to_origin(bottom), "PETG", notes="upright"),
        Part("body_middle", middle, shift_to_origin(middle), "PETG", notes="upright"),
        Part("body_top", top, shift_to_origin(top), "PETG", notes="upright"),
        Part("skin_bottom", assembly["skin_bottom"], skin_print_orientation(skin_bottom), "PETG"),
        Part("gold_bottom", assembly["gold_bottom"], skin_print_orientation(gold_bottom), "Silk PLA"),
        Part("skin_middle", assembly["skin_middle"], skin_print_orientation(skin_middle), "PETG"),
        Part("gold_middle", assembly["gold_middle"], skin_print_orientation(gold_middle), "Silk PLA"),
        Part("skin_top", assembly["skin_top"], skin_print_orientation(skin_top), "PETG"),
        Part("gold_top", assembly["gold_top"], skin_print_orientation(gold_top), "Silk PLA"),
        Part("crown_optional", assembly["crown_optional"], crown_print_orientation(crown), "PETG"),
        Part("scent_tray_optional", tray, shift_to_origin(tray), "PETG"),
    ]
    coupons = [
        Part("joint_coupon_lower", joint_lower, shift_to_origin(joint_lower), "PETG"),
        Part("joint_coupon_upper", joint_upper, shift_to_origin(joint_upper), "PETG"),
        Part("skin_coupon_body", skin_coupon, skin_print_orientation(skin_coupon), "PETG"),
        Part("skin_coupon_gold", skin_coupon_gold, skin_print_orientation(skin_coupon_gold), "Silk PLA"),
    ]
    return BuildResult(p, parts, assembly, coupons)


def export_shape(shape: cq.Shape, path: Path, p: Params) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    suffix = path.suffix.lower()
    if suffix == ".stl":
        cq.exporters.export(
            shape,
            str(path),
            tolerance=p.tessellation_tolerance,
            angularTolerance=p.tessellation_angular_tolerance,
        )
    elif suffix in {".step", ".stp"}:
        cq.exporters.export(shape, str(path), exportType="STEP")
    else:
        raise ValueError(path)


def shape_mesh(shape: cq.Shape, p: Params) -> tuple[np.ndarray, np.ndarray]:
    vertices, triangles = shape.tessellate(
        p.tessellation_tolerance,
        p.tessellation_angular_tolerance,
    )
    vertex_array = np.asarray([[v.x, v.y, v.z] for v in vertices], dtype=float)
    face_array = np.asarray(triangles, dtype=np.int64)
    return vertex_array, face_array


def write_3mf(path: Path, named_shapes: Sequence[tuple[str, cq.Shape, str]], p: Params) -> None:
    ns = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
    ET.register_namespace("", ns)
    model = ET.Element(f"{{{ns}}}model", {"unit": "millimeter", "xml:lang": "en-US"})
    title = ET.SubElement(model, f"{{{ns}}}metadata", {"name": "Title"})
    title.text = "DRAFT ZEN KINTSUGI WAVE FIFO R3.0.0"
    resources = ET.SubElement(model, f"{{{ns}}}resources")
    materials = ET.SubElement(resources, f"{{{ns}}}basematerials", {"id": "1"})
    palette = [
        ("Ivory PETG", "#E5DCCBFF"),
        ("Gold accent", "#C0922CFF"),
        ("Optional accessory", "#C8B99EFF"),
    ]
    for name, color in palette:
        ET.SubElement(materials, f"{{{ns}}}base", {"name": name, "displaycolor": color})
    material_index = {"PETG": 0, "Silk PLA": 1, "Accessory": 2}

    build = ET.SubElement(model, f"{{{ns}}}build")
    for object_id, (name, shape, material) in enumerate(named_shapes, start=2):
        vertices, faces = shape_mesh(shape, p)
        obj = ET.SubElement(
            resources,
            f"{{{ns}}}object",
            {
                "id": str(object_id),
                "type": "model",
                "pid": "1",
                "pindex": str(material_index.get(material, 0)),
                "name": name,
            },
        )
        mesh_node = ET.SubElement(obj, f"{{{ns}}}mesh")
        verts_node = ET.SubElement(mesh_node, f"{{{ns}}}vertices")
        for vertex in vertices:
            ET.SubElement(
                verts_node,
                f"{{{ns}}}vertex",
                {"x": f"{vertex[0]:.6f}", "y": f"{vertex[1]:.6f}", "z": f"{vertex[2]:.6f}"},
            )
        tris_node = ET.SubElement(mesh_node, f"{{{ns}}}triangles")
        for face in faces:
            ET.SubElement(
                tris_node,
                f"{{{ns}}}triangle",
                {"v1": str(int(face[0])), "v2": str(int(face[1])), "v3": str(int(face[2]))},
            )
        ET.SubElement(build, f"{{{ns}}}item", {"objectid": str(object_id)})

    model_bytes = ET.tostring(model, encoding="utf-8", xml_declaration=True)
    content_types = b'''<?xml version="1.0" encoding="UTF-8"?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>'''
    rels = b'''<?xml version="1.0" encoding="UTF-8"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'''
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED, allowZip64=True) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", rels)
        archive.writestr("3D/3dmodel.model", model_bytes)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def build_exports(result: BuildResult, project_root: Path, clean: bool) -> dict:
    export_root = project_root / "exports" / "draft"
    if clean and export_root.exists():
        shutil.rmtree(export_root)
    stl_dir = export_root / "stl"
    step_dir = export_root / "step"
    three_mf_dir = export_root / "3mf"
    for directory in (stl_dir, step_dir, three_mf_dir):
        directory.mkdir(parents=True, exist_ok=True)

    manifest_parts = []
    for part in [*result.parts, *result.coupons]:
        stl_path = stl_dir / f"DRAFT_{part.name}.stl"
        step_path = step_dir / f"DRAFT_{part.name}.step"
        export_shape(part.print_shape, stl_path, result.params)
        export_shape(part.print_shape, step_path, result.params)
        mesh = trimesh.load_mesh(stl_path, force="mesh", process=True)
        bounds = np.round(mesh.bounds, 3).tolist()
        extents = np.round(mesh.extents, 3).tolist()
        manifest_parts.append(
            {
                "name": part.name,
                "quantity": part.quantity,
                "material": part.material,
                "notes": part.notes,
                "stl": str(stl_path.relative_to(project_root)),
                "step": str(step_path.relative_to(project_root)),
                "sha256_stl": file_sha256(stl_path),
                "triangles": int(len(mesh.faces)),
                "watertight": bool(mesh.is_watertight),
                "is_volume": bool(mesh.is_volume),
                "components": int(len(mesh.split(only_watertight=False))),
                "volume_mm3": float(abs(mesh.volume)),
                "bounds_mm": bounds,
                "extents_mm": extents,
            }
        )

    assembly_step = step_dir / "DRAFT_ZEN_KINTSUGI_WAVE_FIFO_R3_assembly.step"
    assembly_compound = cq.Compound.makeCompound(list(result.assembly_shapes.values()))
    export_shape(assembly_compound, assembly_step, result.params)
    assembly_3mf = three_mf_dir / "DRAFT_ZEN_KINTSUGI_WAVE_FIFO_R3_assembly.3mf"
    write_3mf(
        assembly_3mf,
        [
            (name, shape, "Silk PLA" if name.startswith("gold_") else "PETG")
            for name, shape in result.assembly_shapes.items()
        ],
        result.params,
    )
    manifest = {
        "project": "zen-kintsugi-wave-fifo",
        "spec_revision": VERSION,
        "geometry_revision": GEOMETRY_REVISION,
        "status": "DRAFT",
        "source_policy": "fully parametric; no image-to-3D production geometry",
        "parameters": asdict(result.params),
        "parts": manifest_parts,
        "assembly_step": str(assembly_step.relative_to(project_root)),
        "assembly_3mf": str(assembly_3mf.relative_to(project_root)),
        "assembly_step_sha256": file_sha256(assembly_step),
        "assembly_3mf_sha256": file_sha256(assembly_3mf),
    }
    manifest_path = project_root / "validation" / "build-manifest-r3.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--spec", type=Path, default=None)
    parser.add_argument("--clean", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    project_root = args.project_root.resolve()
    spec_path = args.spec.resolve() if args.spec else project_root / "design-spec.yaml"
    params = load_params(spec_path)
    result = build_model(params)
    manifest = build_exports(result, project_root, clean=args.clean)
    print(
        json.dumps(
            {
                "status": manifest["status"],
                "geometry_revision": manifest["geometry_revision"],
                "parts": len(manifest["parts"]),
                "assembly_step": manifest["assembly_step"],
                "assembly_3mf": manifest["assembly_3mf"],
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    main()
