"""Generate an OpenSCAD XY key/pocket fit coupon for an FDM interface.

Each clearance value is per side. Female pockets are open from the top and use a
small lead-in; matching male keys print next to them with a base flange. Print the
coupon with the same machine, nozzle, material, orientation family, and profile as
the real interface. The coupon does not validate load, creep, snap retention, or a
different feature orientation.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


def positive(value: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0:
        raise argparse.ArgumentTypeError("value must be a finite number greater than zero")
    return number


def nonnegative(value: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number < 0:
        raise argparse.ArgumentTypeError("value must be a finite non-negative number")
    return number


def parse_clearances(value: str) -> list[float]:
    try:
        values = [float(item.strip()) for item in value.split(",") if item.strip()]
    except ValueError as exc:
        raise argparse.ArgumentTypeError("clearances must be comma-separated numbers") from exc
    if not values or any(not math.isfinite(item) or item < 0 for item in values):
        raise argparse.ArgumentTypeError("clearances must contain finite non-negative values")
    if len(set(values)) != len(values):
        raise argparse.ArgumentTypeError("clearances must be unique")
    return sorted(values)


def f(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def build_scad(args: argparse.Namespace, clearances: list[float]) -> str:
    max_clearance = max(clearances)
    outer_x = args.key_width_mm + 2 * (args.wall_mm + max_clearance + args.lead_in_mm)
    outer_y = args.key_depth_mm + 2 * (args.wall_mm + max_clearance + args.lead_in_mm)
    outer_z = args.base_mm + args.engagement_mm
    plug_base_x = args.key_width_mm + 2 * args.wall_mm
    plug_base_y = args.key_depth_mm + 2 * args.wall_mm
    stem_height = args.engagement_mm - args.bottom_gap_mm
    gap = args.part_gap_mm
    pitch_x = max(outer_x, plug_base_x) + gap
    plug_y = outer_y + gap

    if stem_height <= 0:
        raise SystemExit("bottom-gap-mm must be smaller than engagement-mm")
    if args.lead_in_mm >= args.engagement_mm:
        raise SystemExit("lead-in-mm must be smaller than engagement-mm")

    clearances_literal = ", ".join(f(value) for value in clearances)
    lines = [
        "// Generated by generate_fit_coupon.py",
        "// Clearance values are PER SIDE in XY.",
        "// Print with the real interface's printer, nozzle, material, orientation family, and profile.",
        "// This coupon does not prove structural load, creep, fatigue, snap force, or other orientations.",
        f"clearances = [{clearances_literal}];",
        f"key_w = {f(args.key_width_mm)};",
        f"key_d = {f(args.key_depth_mm)};",
        f"engagement = {f(args.engagement_mm)};",
        f"wall = {f(args.wall_mm)};",
        f"base = {f(args.base_mm)};",
        f"lead = {f(args.lead_in_mm)};",
        f"bottom_gap = {f(args.bottom_gap_mm)};",
        f"outer_x = {f(outer_x)};",
        f"outer_y = {f(outer_y)};",
        f"outer_z = {f(outer_z)};",
        f"plug_base_x = {f(plug_base_x)};",
        f"plug_base_y = {f(plug_base_y)};",
        f"plug_base_z = {f(args.plug_base_mm)};",
        f"part_gap = {f(gap)};",
        f"pitch_x = {f(pitch_x)};",
        "$fn = 32;",
        "eps = 0.02;",
        "",
        "module pocket(c) {",
        "    pocket_w = key_w + 2*c;",
        "    pocket_d = key_d + 2*c;",
        "    lower_h = engagement - lead + eps;",
        "    translate([(outer_x-pocket_w)/2, (outer_y-pocket_d)/2, base])",
        "        cube([pocket_w, pocket_d, lower_h]);",
        "    if (lead > 0) hull() {",
        "        translate([(outer_x-pocket_w)/2, (outer_y-pocket_d)/2, base+engagement-lead])",
        "            cube([pocket_w, pocket_d, eps]);",
        "        translate([(outer_x-(pocket_w+2*lead))/2, (outer_y-(pocket_d+2*lead))/2, base+engagement])",
        "            cube([pocket_w+2*lead, pocket_d+2*lead, eps]);",
        "    }",
        "}",
        "",
        "module female(c) {",
        "    difference() {",
        "        cube([outer_x, outer_y, outer_z]);",
        "        pocket(c);",
        "        // Engraved per-side clearance label on the front wall.",
        "        translate([outer_x/2, -eps, base+" + f(args.label_size_mm / 2) + "])",
        "            rotate([-90,0,0])",
        f"                linear_extrude(height={f(args.label_depth_mm)}+eps)",
        f"                    text(str(c), size={f(args.label_size_mm)}, halign=\"center\", valign=\"center\");",
        "    }",
        "}",
        "",
        "module male(c) {",
        "    // Print base-down; flip after printing and insert stem-down into the matching pocket.",
        "    union() {",
        "        cube([plug_base_x, plug_base_y, plug_base_z]);",
        "        translate([(plug_base_x-key_w)/2, (plug_base_y-key_d)/2, plug_base_z])",
        "            cube([key_w, key_d, engagement-bottom_gap]);",
        "        translate([plug_base_x/2, (plug_base_y-key_d)/4, plug_base_z])",
        f"            linear_extrude(height={f(args.label_height_mm)})",
        f"                text(str(c), size={f(args.label_size_mm)}, halign=\"center\", valign=\"center\");",
        "    }",
        "}",
        "",
        "for (i = [0 : len(clearances)-1]) {",
        "    c = clearances[i];",
        "    translate([i*pitch_x, 0, 0]) female(c);",
        f"    translate([i*pitch_x + (outer_x-plug_base_x)/2, {f(plug_y)}, 0]) male(c);",
        "}",
        "",
        "echo(\"per-side clearances mm\", clearances);",
        f"echo(\"coupon overall XY mm\", len(clearances)*pitch_x-part_gap, {f(plug_y + plug_base_y)});",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="Output .scad path")
    parser.add_argument("--clearances-mm", type=parse_clearances, default=parse_clearances("0.15,0.25,0.35,0.45"), help="Comma-separated PER-SIDE XY clearances")
    parser.add_argument("--key-width-mm", type=positive, default=10.0)
    parser.add_argument("--key-depth-mm", type=positive, default=6.0)
    parser.add_argument("--engagement-mm", type=positive, default=8.0)
    parser.add_argument("--wall-mm", type=positive, default=3.0)
    parser.add_argument("--base-mm", type=positive, default=2.0, help="Female pocket floor thickness")
    parser.add_argument("--lead-in-mm", type=nonnegative, default=0.8)
    parser.add_argument("--bottom-gap-mm", type=nonnegative, default=0.5)
    parser.add_argument("--plug-base-mm", type=positive, default=2.0)
    parser.add_argument("--part-gap-mm", type=positive, default=5.0)
    parser.add_argument("--label-size-mm", type=positive, default=2.6)
    parser.add_argument("--label-depth-mm", type=positive, default=0.4)
    parser.add_argument("--label-height-mm", type=positive, default=0.35)
    args = parser.parse_args()

    if args.output.suffix.lower() != ".scad":
        raise SystemExit("--output must end in .scad")
    content = build_scad(args, args.clearances_mm)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} with {len(args.clearances_mm)} per-side clearances")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
